import {
  createServer,
  type Server as HttpServer,
  type IncomingMessage,
  type ServerResponse,
} from "node:http";
import {
  closeSync,
  existsSync,
  openSync,
  readFileSync,
  readSync,
  statSync,
} from "node:fs";
import { timingSafeEqual } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve, sep } from "node:path";
import {
  executeChatGptCli,
  readConnectionReceipt,
  refreshChatGptLifecycle,
} from "../chatgpt/cli.js";
import {
  deriveChatGptLifecycle,
  redactSensitive,
  redactSensitiveText,
  type ChatGptLifecycleSnapshot,
} from "../chatgpt/lifecycle.js";
import type { Container } from "../runtime/container.js";
import type { ToolRegistry } from "../tools/registry.js";
import type { PolicyMode, ToolPrincipal } from "../core/types.js";
import { adminPrincipalFromCredential } from "../core/principal.js";
import { ApprovalResolutionError } from "../policy/approvals.js";
import { logger } from "../core/logger.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

export interface DashboardOptions {
  host: string;
  port: number;
  /**
   * Bearer token required on every request when the bind host is NOT loopback.
   * Loopback binds (127.0.0.1, ::1, localhost) skip auth. If omitted for a
   * non-loopback bind, one is generated by the caller.
   */
  token?: string;
}

/** True when the bind host is loopback-only and therefore safe without a token. */
export function isLoopbackHost(host: string): boolean {
  return host === "127.0.0.1" || host === "::1" || host === "localhost";
}

/**
 * Local control-plane dashboard. Read-only views plus approval actions.
 *
 * Endpoints:
 *   GET  /            -> static dashboard (dashboard/static/index.html)
 *   GET  /status      -> server + workspace + policy snapshot
 *   GET  /audit       -> recent audit events
 *   GET  /processes   -> managed long-running processes
 *   GET  /approvals   -> pending + resolved approval requests
 *   POST /approvals/:id/approve  -> approve (body: { scope?: 'once'|'session' })
 *   POST /approvals/:id/deny     -> deny
 *   POST /policy/mode             -> change runtime policy mode (admin only)
 */
export function startDashboard(
  container: Container,
  registry: ToolRegistry,
  opts: DashboardOptions,
): HttpServer {
  // Auth is enforced only when bound to a non-loopback address. A loopback bind
  // is treated as trusted (same machine), matching the default 127.0.0.1.
  const requireAuth = !isLoopbackHost(opts.host);
  if (requireAuth && !opts.token) {
    throw new Error("Dashboard bound to a non-loopback host requires a token");
  }

  const server = createServer((req, res) => {
    const credential = extractDashboardCredential(req);
    if (
      requireAuth &&
      (!credential || !timingSafeEqualStr(credential, opts.token!))
    ) {
      res.writeHead(401, {
        "content-type": "application/json; charset=utf-8",
        "www-authenticate": 'Bearer realm="folderforge-dashboard"',
      });
      res.end(
        JSON.stringify({
          error: "unauthorized",
          message: "Valid bearer token required.",
        }),
      );
      return;
    }
    const principal = adminPrincipalFromCredential(
      requireAuth ? credential : undefined,
    );
    handle(req, res, container, registry, principal).catch((err) => {
      logger.error({ err: String(err) }, "Dashboard request failed");
      sendJson(res, 500, { error: "internal_error", message: String(err) });
    });
  });

  server.listen(opts.port, opts.host, () => {
    logger.info(
      { host: opts.host, port: opts.port, authRequired: requireAuth },
      "Dashboard listening",
    );
  });

  return server;
}

/**
 * Accept the token via either `Authorization: Bearer <token>` or a `?token=`
 * query parameter (handy for opening the dashboard in a browser). Comparison is
 * constant-time to avoid leaking the token length/prefix via timing.
 */
function extractDashboardCredential(req: IncomingMessage): string | undefined {
  const header = req.headers["authorization"];
  if (typeof header === "string" && header.startsWith("Bearer ")) {
    const credential = header.slice("Bearer ".length).trim();
    if (credential) return credential;
  }
  const url = new URL(req.url ?? "/", "http://localhost");
  return url.searchParams.get("token") ?? undefined;
}

function timingSafeEqualStr(a: string, b: string): boolean {
  const ab = Buffer.from(a);
  const bb = Buffer.from(b);
  if (ab.length !== bb.length) return false;
  return timingSafeEqual(ab, bb);
}

interface DashboardChatGptAction {
  id: string;
  label: string;
  mode: "automatic" | "manual" | "client";
  command?: string;
  explanation?: string;
}

interface DashboardChatGptStatus {
  configured: boolean;
  status: ChatGptLifecycleSnapshot["overall"] | "unconfigured";
  state: ChatGptLifecycleSnapshot["state"];
  summary: string;
  mcpUrl?: string;
  timeline: ChatGptLifecycleSnapshot["timeline"];
  diagnostics: ChatGptLifecycleSnapshot["diagnostics"];
  actions: DashboardChatGptAction[];
  configuration: Record<string, unknown>;
  lastChecked: string;
}

function processAlive(pid?: number): boolean {
  if (!pid || !Number.isInteger(pid) || pid <= 0) return false;
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

function quoteCliPath(path: string): string {
  return JSON.stringify(path);
}

function actionDescriptor(
  action: string,
  projectRoot: string,
): DashboardChatGptAction {
  const project = quoteCliPath(projectRoot);
  const definitions: Record<string, DashboardChatGptAction> = {
    start_server: {
      id: "start_server",
      label: "Start server",
      mode: "manual",
      command: `folderforge chatgpt start --project ${project}`,
      explanation:
        "Starting or replacing the process that serves this dashboard must be done from a terminal.",
    },
    restart_server: {
      id: "restart_server",
      label: "Restart server",
      mode: "manual",
      command: `folderforge chatgpt start --project ${project}`,
      explanation:
        "Restarting this process from its own dashboard would interrupt the response.",
    },
    restart_tunnel: {
      id: "restart_tunnel",
      label: "Restart tunnel",
      mode: "manual",
      command: `folderforge chatgpt repair --project ${project}`,
      explanation:
        "A temporary tunnel restart can change the MCP resource URL and requires a new ChatGPT DCR client.",
    },
    repair_auth0: {
      id: "repair_auth0",
      label: "Repair Auth0",
      mode: "automatic",
    },
    enable_login_connection: {
      id: "enable_login_connection",
      label: "Enable login connection",
      mode: "automatic",
    },
    repair_user_grant: {
      id: "repair_user_grant",
      label: "Repair user grant",
      mode: "automatic",
    },
    wait_for_dcr_client: {
      id: "wait_for_dcr_client",
      label: "Wait for DCR client",
      mode: "automatic",
      explanation: "Click Connect in ChatGPT while this action is running.",
    },
    rerun_verification: {
      id: "rerun_verification",
      label: "Re-run verification",
      mode: "automatic",
    },
    copy_mcp_url: {
      id: "copy_mcp_url",
      label: "Copy MCP URL",
      mode: "client",
    },
  };
  return (
    definitions[action] ?? {
      id: action,
      label: action.replace(/_/g, " "),
      mode: "manual",
    }
  );
}

function lifecycleSummary(snapshot: ChatGptLifecycleSnapshot): string {
  if (snapshot.overall === "connected")
    return "ChatGPT is authenticated and MCP is ready.";
  if (snapshot.state === "READY_TO_COMPLETE_LOGIN") {
    return "OAuth is ready. Return to ChatGPT and complete sign-in.";
  }
  if (snapshot.state === "WAITING_FOR_CHATGPT_CLIENT") {
    return "Waiting for ChatGPT to register an OAuth client.";
  }
  if (snapshot.overall === "stopped")
    return "The local server or public tunnel is stopped.";
  return "The ChatGPT connection needs attention. Review diagnostics and run the suggested repair.";
}

function unconfiguredChatGptStatus(
  container: Container,
): DashboardChatGptStatus {
  const snapshot = deriveChatGptLifecycle({
    receiptExists: false,
    serverAlive: false,
    tunnelRequired: false,
    tunnelAlive: false,
    checks: {},
  });
  return {
    configured: false,
    status: "unconfigured",
    state: snapshot.state,
    summary: "ChatGPT is not configured. Run `folderforge connect chatgpt`.",
    timeline: snapshot.timeline,
    diagnostics: snapshot.diagnostics,
    actions: [
      {
        id: "connect_chatgpt",
        label: "Connect ChatGPT",
        mode: "manual",
        command: `folderforge connect chatgpt --project ${quoteCliPath(container.projectRoot())}`,
      },
    ],
    configuration: {
      projectRoot: container.projectRoot(),
      policyMode: container.policy.getMode(),
      enabledAdapters: Object.entries(container.config.adapters)
        .filter(([, value]) => Boolean(value?.enabled))
        .map(([name]) => name),
    },
    lastChecked: new Date().toISOString(),
  };
}

function chatGptStatus(container: Container): DashboardChatGptStatus {
  const receiptPath = join(
    container.projectRoot(),
    ".folderforge",
    "chatgpt-connection.json",
  );
  if (!existsSync(receiptPath)) return unconfiguredChatGptStatus(container);
  const receipt = readConnectionReceipt(receiptPath);
  const serverAlive = processAlive(receipt.processes.serverPid);
  const tunnelAlive =
    receipt.connectivity.kind !== "cloudflared-quick" ||
    processAlive(receipt.processes.tunnelPid);
  const snapshot = refreshChatGptLifecycle(receipt, serverAlive, tunnelAlive);
  const actionIds = new Set(snapshot.actions);
  actionIds.add("copy_mcp_url");
  if (serverAlive) actionIds.add("restart_server");
  const localPort = (() => {
    try {
      return Number(new URL(receipt.connectivity.localUrl).port) || null;
    } catch {
      return null;
    }
  })();
  return redactSensitive({
    configured: true,
    status: snapshot.overall,
    state: snapshot.state,
    summary: lifecycleSummary(snapshot),
    mcpUrl: receipt.mcpUrl,
    timeline: snapshot.timeline,
    diagnostics: snapshot.diagnostics,
    actions: [...actionIds].map((action) =>
      actionDescriptor(action, receipt.projectRoot),
    ),
    configuration: {
      projectRoot: receipt.projectRoot,
      port: localPort,
      publicUrl: receipt.connectivity.publicUrl,
      tenant: receipt.tenant,
      profile: receipt.runtime?.profile ?? null,
      policyMode: receipt.runtime?.policyMode ?? container.policy.getMode(),
      resourcePolicy: receipt.runtime?.dcrClientPolicy ?? null,
      toolPreset: receipt.runtime?.toolsPreset ?? null,
      enabledAdapters: receipt.runtime?.adapters ?? [],
      loginConnections: receipt.runtime?.loginConnections ?? [],
      registration: receipt.registration,
      connectivity: receipt.connectivity.kind,
    },
    lastChecked: snapshot.updatedAt,
  });
}

function boundedLogTail(
  path: string,
  projectRoot: string,
  limit: number,
): string[] {
  const root = resolve(projectRoot);
  const target = resolve(path);
  if (target !== root && !target.startsWith(`${root}${sep}`)) {
    throw new Error("Log path is outside the active project boundary.");
  }
  if (!existsSync(target)) return [];
  const size = statSync(target).size;
  const bytesToRead = Math.min(size, 256 * 1024);
  const buffer = Buffer.alloc(bytesToRead);
  const fd = openSync(target, "r");
  try {
    readSync(fd, buffer, 0, bytesToRead, Math.max(0, size - bytesToRead));
  } finally {
    closeSync(fd);
  }
  return buffer
    .toString("utf8")
    .split("\n")
    .slice(size > bytesToRead ? 1 : 0)
    .filter(Boolean)
    .slice(-limit)
    .map(redactSensitiveText);
}

async function runChatGptDashboardAction(
  action: string,
  container: Container,
): Promise<{ status: number; body: Record<string, unknown> }> {
  const root = container.projectRoot();
  if (
    action === "start_server" ||
    action === "restart_server" ||
    action === "restart_tunnel"
  ) {
    const descriptor = actionDescriptor(action, root);
    return {
      status: 202,
      body: {
        accepted: false,
        requiresTerminal: true,
        action: descriptor,
      },
    };
  }
  const commandArgs: Record<string, string[]> = {
    rerun_verification: ["status", "--project", root, "--json"],
    repair_auth0: [
      "repair",
      "--project",
      root,
      "--no-start",
      "--no-wait",
      "--json",
    ],
    enable_login_connection: [
      "repair",
      "--project",
      root,
      "--no-start",
      "--no-wait",
      "--json",
    ],
    repair_user_grant: [
      "repair",
      "--project",
      root,
      "--no-start",
      "--no-wait",
      "--json",
    ],
    wait_for_dcr_client: [
      "repair",
      "--project",
      root,
      "--no-start",
      "--wait",
      "--wait-timeout",
      "60",
      "--poll-interval",
      "2",
      "--json",
    ],
  };
  const args = commandArgs[action];
  if (!args) {
    return { status: 404, body: { error: "unknown_chatgpt_action", action } };
  }
  const result = await executeChatGptCli(args, { cwd: root });
  return {
    status: result.exitCode === 0 ? 200 : 409,
    body: redactSensitive({
      ok: result.exitCode === 0,
      output: result.output,
      status: result.receipt?.lifecycleSnapshot ?? null,
    }),
  };
}

async function runOperatorTool(
  registry: ToolRegistry,
  container: Container,
  principal: ToolPrincipal,
  tool: string,
  args: Record<string, unknown>,
) {
  const actionPrincipal: ToolPrincipal = {
    ...principal,
    id: `${principal.id}:operator-action`,
    sessionId: `${principal.id}:dashboard-session`,
  };
  let result = await registry.call(tool, args, { principal: actionPrincipal });
  if (result.approvalId) {
    const approval = container.policy.approvals.approve(
      result.approvalId,
      'once',
      principal.id,
    );
    container.audit.record({
      type: 'approval_resolved',
      summary: `operator approve ${result.approvalId} (once)`,
      detail: {
        approvalId: result.approvalId,
        approverId: principal.id,
        requesterId: approval?.requesterId,
        binding: approval?.binding,
      },
    });
    result = await registry.call(tool, args, { principal: actionPrincipal });
  }
  return result;
}

async function handle(
  req: IncomingMessage,
  res: ServerResponse,
  container: Container,
  registry: ToolRegistry,
  principal: ToolPrincipal,
): Promise<void> {
  const method = req.method ?? "GET";
  const url = new URL(req.url ?? "/", "http://localhost");
  const path = url.pathname;

  if (method === "GET" && (path === "/" || path === "/index.html")) {
    return sendStatic(res);
  }

  if (method === "GET" && path === "/status") {
    const active = container.workspace.getActive();
    return sendJson(res, 200, {
      server: {
        name: container.config.server.name,
        transport: container.config.server.transport,
      },
      workspace: {
        active: Boolean(active),
        projectRoot: container.projectRoot(),
        name: active?.name ?? null,
        languageHints: active?.languageHints ?? [],
        startupError: container.workspaceStartupError,
        allowedDirectories: container.config.workspace.allowedDirectories,
      },
      policy: container.policy.describe(),
      capsules: container.capsules.describe(),
      isolation: container.isolation.describe(),
      tools: {
        active: registry.listActive().length,
        total: registry.listAll().length,
      },
    });
  }

  if (method === "GET" && path === "/chatgpt/status") {
    return sendJson(res, 200, chatGptStatus(container));
  }

  if (method === "GET" && path === "/chatgpt/logs") {
    const receiptPath = join(
      container.projectRoot(),
      ".folderforge",
      "chatgpt-connection.json",
    );
    if (!existsSync(receiptPath)) {
      return sendJson(res, 404, { error: "chatgpt_not_configured" });
    }
    const subsystem = url.searchParams.get("subsystem") ?? "server";
    if (subsystem !== "server" && subsystem !== "tunnel") {
      return sendJson(res, 400, { error: "invalid_log_subsystem", subsystem });
    }
    const receipt = readConnectionReceipt(receiptPath);
    const logPath =
      subsystem === "server"
        ? receipt.processes.serverLog
        : receipt.processes.tunnelLog;
    const limit = clampInt(url.searchParams.get("limit"), 120, 1, 500);
    const lines = logPath
      ? boundedLogTail(logPath, receipt.projectRoot, limit)
      : [];
    return sendJson(res, 200, { subsystem, lines });
  }

  const chatGptActionMatch = /^\/chatgpt\/actions\/([^/]+)$/.exec(path);
  if (method === "POST" && chatGptActionMatch) {
    const action = decodeURIComponent(chatGptActionMatch[1]!);
    const result = await runChatGptDashboardAction(action, container);
    container.audit.record({
      type: "process_event",
      summary: `chatgpt_dashboard_action:${action}`,
      ok: result.status < 400,
      detail: { actorId: principal.id, action, status: result.status },
    });
    return sendJson(res, result.status, result.body);
  }

  if (method === "GET" && path === "/audit") {
    const limit = clampInt(url.searchParams.get("limit"), 50, 1, 500);
    return sendJson(
      res,
      200,
      redactSensitive({ entries: container.audit.recent(limit) }),
    );
  }

  if (method === "GET" && path === "/processes") {
    return sendJson(res, 200, { processes: container.processes.list() });
  }

  if (method === "GET" && path === "/isolations") {
    return sendJson(res, 200, {
      ...container.isolation.describe(),
      isolations: container.isolation.list(),
    });
  }

  if (method === "POST" && path === "/isolations") {
    const body = await readJsonBody(req);
    const result = await runOperatorTool(registry, container, principal, 'isolation_create', {
      taskId: String(body?.taskId ?? ''),
      baseRef: String(body?.baseRef ?? 'HEAD'),
    });
    return sendJson(res, result.ok ? 201 : 409, result);
  }

  const isolationReadMatch = /^\/isolations\/([^/]+)\/(status|diff)$/.exec(path);
  if (method === "GET" && isolationReadMatch) {
    const id = decodeURIComponent(isolationReadMatch[1]!);
    const tool = isolationReadMatch[2] === 'diff' ? 'isolation_diff' : 'isolation_status';
    const result = await runOperatorTool(registry, container, principal, tool, { id });
    return sendJson(res, result.ok ? 200 : 409, result);
  }

  const isolationActionMatch = /^\/isolations\/([^/]+)\/(apply|rollback|discard)$/.exec(path);
  if (method === "POST" && isolationActionMatch) {
    const id = decodeURIComponent(isolationActionMatch[1]!);
    const action = isolationActionMatch[2];
    const tool = action === 'apply'
      ? 'isolation_apply'
      : action === 'rollback'
        ? 'isolation_rollback'
        : 'isolation_discard';
    const result = await runOperatorTool(registry, container, principal, tool, { id });
    return sendJson(res, result.ok ? 200 : 409, result);
  }

  if (method === "GET" && path === "/approvals") {
    return sendJson(res, 200, {
      pending: container.policy.approvals.pending(),
      all: container.policy.approvals.all(),
    });
  }

  if (method === "GET" && path === "/capsules") {
    return sendJson(res, 200, {
      ...container.capsules.describe(),
      capsules: container.capsules.list(),
    });
  }

  if (method === "POST" && path === "/capsules") {
    const body = await readJsonBody(req);
    try {
      const capsule = container.capsules.create({
        workspaceRoot: String(body?.workspaceRoot ?? container.projectRoot()),
        principalId: String(body?.principalId ?? ""),
        profile: String(body?.profile ?? "") as import('../capsule/workspace-capsule-manager.js').PermissionProfile,
        ...(body?.ttlMs !== undefined ? { ttlMs: Number(body.ttlMs) } : {}),
        ...(typeof body?.sessionId === "string" ? { sessionId: body.sessionId } : {}),
        ...(typeof body?.clientId === "string" ? { clientId: body.clientId } : {}),
        ...(typeof body?.taskId === "string" ? { taskId: body.taskId } : {}),
        ...(Array.isArray(body?.grantedScopes)
          ? { grantedScopes: body.grantedScopes.map(String) }
          : {}),
        ...(typeof body?.isolation === "string"
          ? { isolation: body.isolation as import('../capsule/workspace-capsule-manager.js').CapsuleIsolation }
          : {}),
        ...(typeof body?.networkPolicy === "string"
          ? { networkPolicy: body.networkPolicy as import('../capsule/workspace-capsule-manager.js').CapsuleNetworkPolicy }
          : {}),
        ...(body?.limits && typeof body.limits === "object"
          ? { limits: body.limits as Partial<import('../capsule/workspace-capsule-manager.js').CapsuleLimits> }
          : {}),
        ...(typeof body?.evidenceDestination === "string"
          ? { evidenceDestination: body.evidenceDestination }
          : {}),
        ...(typeof body?.clientCompatibility === "string"
          ? { clientCompatibility: body.clientCompatibility as import('../capsule/workspace-capsule-manager.js').ClientCompatibilityProfile }
          : {}),
      });
      container.audit.record({
        type: "policy_change",
        summary: `capsule_created:${capsule.id}`,
        detail: {
          actorId: principal.id,
          capsuleId: capsule.id,
          principalId: capsule.principalId,
          profile: capsule.profile,
          workspaceId: capsule.workspaceId,
        },
      });
      return sendJson(res, 201, { capsule });
    } catch (error) {
      return sendJson(res, 400, {
        error: "invalid_capsule",
        message: error instanceof Error ? error.message : String(error),
      });
    }
  }

  const capsuleMatch = /^\/capsules\/([^/]+)\/revoke$/.exec(path);
  if (method === "POST" && capsuleMatch) {
    const id = decodeURIComponent(capsuleMatch[1]!);
    const capsule = container.capsules.revoke(id, principal.id);
    if (!capsule) return sendJson(res, 404, { error: "capsule_not_found", id });
    container.audit.record({
      type: "policy_change",
      summary: `capsule_revoked:${id}`,
      detail: { actorId: principal.id, capsuleId: id },
    });
    return sendJson(res, 200, { capsule });
  }

  // POST /approvals/:id/approve | /approvals/:id/deny
  const approvalMatch = /^\/approvals\/([^/]+)\/(approve|deny)$/.exec(path);
  if (method === "POST" && approvalMatch) {
    const id = approvalMatch[1]!;
    const action = approvalMatch[2]!;
    const body = await readJsonBody(req);
    let result;
    try {
      if (action === "approve") {
        const scope = body?.scope === "session" ? "session" : "once";
        result = container.policy.approvals.approve(id, scope, principal.id);
      } else {
        result = container.policy.approvals.deny(id, principal.id);
      }
    } catch (error) {
      if (error instanceof ApprovalResolutionError) {
        return sendJson(res, 409, {
          error: error.code,
          message: error.message,
          id,
        });
      }
      throw error;
    }
    if (!result) {
      return sendJson(res, 404, { error: "approval_not_found", id });
    }
    container.audit.record({
      type: "approval_resolved",
      tool: result.tool,
      risk: result.risk,
      summary: `${action} (${result.state})`,
      detail: { approvalId: id, approverId: principal.id },
    });
    return sendJson(res, 200, { approval: result });
  }

  if (method === "POST" && path === "/policy/mode") {
    const body = await readJsonBody(req);
    const mode = String(body?.mode ?? "") as PolicyMode;
    if (!["readonly", "safe", "dev", "danger"].includes(mode)) {
      return sendJson(res, 400, { error: "invalid_policy_mode", mode });
    }
    container.policy.setMode(mode);
    container.audit.record({
      type: "policy_change",
      summary: `mode=${mode}`,
      detail: { actorId: principal.id, mode },
    });
    return sendJson(res, 200, { mode });
  }

  sendJson(res, 404, { error: "not_found", path });
}

function sendStatic(res: ServerResponse): void {
  const candidates = [
    join(__dirname, "static", "index.html"),
    join(process.cwd(), "src", "dashboard", "static", "index.html"),
  ];
  for (const file of candidates) {
    if (existsSync(file)) {
      const html = readFileSync(file, "utf8");
      res.writeHead(200, { "content-type": "text/html; charset=utf-8" });
      res.end(html);
      return;
    }
  }
  res.writeHead(404, { "content-type": "text/plain; charset=utf-8" });
  res.end("Dashboard static asset not found");
}

function sendJson(res: ServerResponse, status: number, body: unknown): void {
  res.writeHead(status, { "content-type": "application/json; charset=utf-8" });
  res.end(JSON.stringify(body, null, 2));
}

async function readJsonBody(
  req: IncomingMessage,
): Promise<Record<string, unknown> | null> {
  return new Promise((resolveBody) => {
    let raw = "";
    req.on("data", (chunk) => {
      raw += chunk;
      if (raw.length > 1_000_000) req.destroy();
    });
    req.on("end", () => {
      if (!raw.trim()) return resolveBody(null);
      try {
        resolveBody(JSON.parse(raw) as Record<string, unknown>);
      } catch {
        resolveBody(null);
      }
    });
    req.on("error", () => resolveBody(null));
  });
}

function clampInt(
  value: string | null,
  fallback: number,
  min: number,
  max: number,
): number {
  const n = value ? Number(value) : NaN;
  if (!Number.isFinite(n)) return fallback;
  return Math.min(max, Math.max(min, Math.floor(n)));
}
