import {
  createServer,
  type Server as HttpServer,
  type IncomingMessage,
  type ServerResponse,
} from "node:http";
import {
  closeSync,
  existsSync,
  lstatSync,
  mkdirSync,
  openSync,
  readdirSync,
  readFileSync,
  readSync,
  statSync,
} from "node:fs";
import { timingSafeEqual } from "node:crypto";
import { homedir } from "node:os";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve, sep } from "node:path";
import {
  executeChatGptCli,
  readConnectionReceipt,
  refreshChatGptLifecycle,
} from "../chatgpt/cli.js";
import {
  deriveChatGptLifecycle,
  redactSensitive,
  redactSensitiveText,
  type ChatGptLifecycleSnapshot,
} from "../chatgpt/lifecycle.js";
import type { Container } from "../runtime/container.js";
import type { ToolRegistry } from "../tools/registry.js";
import type { PolicyMode, ToolPrincipal } from "../core/types.js";
import { adminPrincipalFromCredential } from "../core/principal.js";
import { ApprovalResolutionError } from "../policy/approvals.js";
import { makeCloudflareClient } from "../cloudflare/api-client.js";
import { clearCloudflareConfig, maskedCloudflareConfig, saveCloudflareConfig } from "../cloudflare/config-store.js";
import { logger } from "../core/logger.js";
import { MISSION_CONTROL_OPERATOR_ROLE } from "../operator/mission-control.js";
import { GROUP_PRESETS, resolveActiveTools } from "../tools/index.js";
import { readFolderForgeVersion } from "../core/version.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

export interface DashboardOptions {
  host: string;
  port: number;
  /**
   * Bearer token required on every request when the bind host is NOT loopback.
   * Loopback binds (127.0.0.1, ::1, localhost) skip auth. If omitted for a
   * non-loopback bind, one is generated by the caller.
   */
  token?: string;
}

/** True when the bind host is loopback-only and therefore safe without a token. */
export function isLoopbackHost(host: string): boolean {
  return host === "127.0.0.1" || host === "::1" || host === "localhost";
}

/**
 * Local control-plane dashboard. Read-only views plus approval actions.
 *
 * Endpoints:
 *   GET  /            -> 308 redirect to /app/ (Mission Control SPA)
 *   GET  /app         -> Mission Control SPA (packages/mission-control build, when present)
 *   GET  /status      -> server + workspace + policy snapshot
 *   GET  /audit       -> recent audit events
 *   GET  /processes   -> managed long-running processes
 *   GET  /approvals   -> pending + resolved approval requests
 *   POST /approvals/:id/approve  -> approve (body: { scope?: 'once'|'session' })
 *   POST /approvals/:id/deny     -> deny
 *   POST /policy/mode             -> change runtime policy mode (admin only)
 *   GET  /fleet                    -> provisioned per-folder MCP instances
 *   POST /fleet                    -> provision a folder (body: { projectPath, name?, toolsPreset?, policyMode? })
 *   POST /fleet/:id/start|stop|restart -> instance lifecycle (governed via provision_* tools)
 *   POST /fleet/:id/auto-restart   -> toggle auto-restart (body: { enabled: boolean })
 *   POST /fleet/:id/preset         -> change tool preset (body: { toolsPreset }); applies on next start
 *   POST /fleet/:id/policy         -> change policy mode (body: { policyMode }); applies on next start
 *   POST /fleet/:id/rotate-token   -> rotate the instance bearer token (HIGH; returned once)
 *   POST /fleet/:id/tunnel         -> expose the running instance publicly; body { hostname } upgrades to a named Cloudflare tunnel + DNS (HIGH)
 *   GET  /fleet/:id/logs           -> non-consuming tail of the instance process log
 *   GET  /tools                    -> tool catalog with groups, risk, and preset coverage
 *   GET  /plugins                  -> installed plugins (via plugin_list)
 *   GET  /marketplace              -> marketplace index entries (via marketplace_list)
 *   POST /plugins/:id/enable|disable -> plugin lifecycle (governed via plugin_enable/disable)
 *   GET  /workspaces               -> activated workspaces (via workspace_list)
 *   POST /workspaces/switch        -> switch current workspace (body: { path })
 *   POST /workspaces/activate      -> activate a folder as a workspace (body: { path })
 *   POST /fs/browse                -> list subdirectories under the widest governable dir (body: { path? })
 *   POST /fs/mkdir                 -> create a directory under that same bound (body: { path, name })
 *   GET  /tunnels                  -> quick tunnels (via tunnel_list)
 *   POST /tunnels                  -> expose a port publicly (body: { targetPort }) HIGH risk
 *   POST /tunnels/:id/stop         -> close a tunnel; body { cleanup: true } also deletes the Cloudflare DNS record + tunnel for named ones
 *   GET  /cloudflare/status        -> linked Cloudflare account (masked; the token is never returned)
 *   POST /cloudflare/config        -> link an account: { apiToken, accountId, domain } (token verified, zone resolved, stored 0600)
 *   DELETE /cloudflare/config      -> unlink the account
 */
export function startDashboard(
  container: Container,
  registry: ToolRegistry,
  opts: DashboardOptions,
): HttpServer {
  // Auth is enforced only when bound to a non-loopback address. A loopback bind
  // is treated as trusted (same machine), matching the default 127.0.0.1.
  const requireAuth = !isLoopbackHost(opts.host);
  if (requireAuth && !opts.token) {
    throw new Error("Dashboard bound to a non-loopback host requires a token");
  }

  const server = createServer((req, res) => {
    const credential = extractDashboardCredential(req);
    if (
      requireAuth &&
      (!credential || !timingSafeEqualStr(credential, opts.token!))
    ) {
      res.writeHead(401, {
        "content-type": "application/json; charset=utf-8",
        "www-authenticate": 'Bearer realm="folderforge-dashboard"',
      });
      res.end(
        JSON.stringify({
          error: "unauthorized",
          message: "Valid bearer token required.",
        }),
      );
      return;
    }
    const principal = adminPrincipalFromCredential(
      requireAuth ? credential : undefined,
    );
    handle(req, res, container, registry, principal).catch((err) => {
      logger.error({ err: String(err) }, "Dashboard request failed");
      sendJson(res, 500, { error: "internal_error", message: String(err) });
    });
  });

  server.listen(opts.port, opts.host, () => {
    logger.info(
      { host: opts.host, port: opts.port, authRequired: requireAuth },
      "Dashboard listening",
    );
  });

  return server;
}

/**
 * Accept the token via either `Authorization: Bearer <token>` or a `?token=`
 * query parameter (handy for opening the dashboard in a browser). Comparison is
 * constant-time to avoid leaking the token length/prefix via timing.
 */
function extractDashboardCredential(req: IncomingMessage): string | undefined {
  const header = req.headers["authorization"];
  if (typeof header === "string" && header.startsWith("Bearer ")) {
    const credential = header.slice("Bearer ".length).trim();
    if (credential) return credential;
  }
  const url = new URL(req.url ?? "/", "http://localhost");
  return url.searchParams.get("token") ?? undefined;
}

/** All directories the operator lets this control plane govern (resolved). */
function fsAllowedRoots(container: Container): string[] {
  const dirs = container.config.workspace.allowedDirectories ?? [];
  if (dirs.length > 0) return dirs.map((d) => resolve(d));
  try {
    return [defaultBrowsePoint()];
  } catch {
    return [container.projectRoot()];
  }
}

/** Display root for the SPA picker: the primary governable directory. */
function fsBrowsePoint(container: Container): string {
  return fsAllowedRoots(container)[0] ?? container.projectRoot();
}

/** Best-effort default: ~/Desktop when it exists, else the home directory. */
function defaultBrowsePoint(): string {
  const desktop = join(homedir(), "Desktop");
  return existsSync(desktop) && statSync(desktop).isDirectory() ? desktop : homedir();
}

/** True when `target` equals or sits inside `root`. */
function isWithinDir(root: string, target: string): boolean {
  const from = resolve(root);
  const to = resolve(target);
  return to === from || to.startsWith(from + sep);
}

/**
 * Serve the Mission Control SPA (built from packages/mission-control) under
 * /app. Prefers the packaged build output (dist/dashboard/app) and falls back
 * to the in-repo package dist when running from a checkout. 404 with build
 * instructions when the SPA has not been built.
 */
function serveMissionControlApp(res: ServerResponse, path: string): void {
  const relative = path === "/app" || path === "/app/" ? "index.html" : path.slice("/app/".length);
  if (relative.includes("..")) {
    res.writeHead(400, { "content-type": "text/plain" });
    res.end("bad path");
    return;
  }
  const roots = [
    join(__dirname, "app"),
    join(process.cwd(), "packages", "mission-control", "dist"),
  ];
  for (const rootDir of roots) {
    const file = join(rootDir, relative);
    if (existsSync(file) && statSync(file).isFile()) {
      const type = relative.endsWith(".js")
        ? "text/javascript"
        : relative.endsWith(".css")
          ? "text/css"
          : relative.endsWith(".svg")
            ? "image/svg+xml"
            : relative.endsWith(".json")
              ? "application/json"
              : "text/html; charset=utf-8";
      res.writeHead(200, { "content-type": type });
      res.end(readFileSync(file));
      return;
    }
  }
  // Client-side routes (e.g. /app/fleet) have no asset file: fall back to the SPA shell.
  if (!/\.[a-z0-9]+$/i.test(relative)) {
    for (const rootDir of roots) {
      const file = join(rootDir, "index.html");
      if (existsSync(file) && statSync(file).isFile()) {
        res.writeHead(200, { "content-type": "text/html; charset=utf-8" });
        res.end(readFileSync(file));
        return;
      }
    }
  }
  res.writeHead(404, { "content-type": "text/plain" });
  res.end(
    "Mission Control app not built. Run: npm --prefix packages/mission-control install && npm run build:mission-control",
  );
}

function timingSafeEqualStr(a: string, b: string): boolean {
  const ab = Buffer.from(a);
  const bb = Buffer.from(b);
  if (ab.length !== bb.length) return false;
  return timingSafeEqual(ab, bb);
}

interface DashboardChatGptAction {
  id: string;
  label: string;
  mode: "automatic" | "manual" | "client";
  command?: string;
  explanation?: string;
}

interface DashboardChatGptStatus {
  configured: boolean;
  status: ChatGptLifecycleSnapshot["overall"] | "unconfigured";
  state: ChatGptLifecycleSnapshot["state"];
  summary: string;
  mcpUrl?: string;
  timeline: ChatGptLifecycleSnapshot["timeline"];
  diagnostics: ChatGptLifecycleSnapshot["diagnostics"];
  actions: DashboardChatGptAction[];
  configuration: Record<string, unknown>;
  lastChecked: string;
}

function processAlive(pid?: number): boolean {
  if (!pid || !Number.isInteger(pid) || pid <= 0) return false;
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

function quoteCliPath(path: string): string {
  return JSON.stringify(path);
}

function actionDescriptor(
  action: string,
  projectRoot: string,
): DashboardChatGptAction {
  const project = quoteCliPath(projectRoot);
  const definitions: Record<string, DashboardChatGptAction> = {
    start_server: {
      id: "start_server",
      label: "Start server",
      mode: "manual",
      command: `folderforge chatgpt start --project ${project}`,
      explanation:
        "Starting or replacing the process that serves this dashboard must be done from a terminal.",
    },
    restart_server: {
      id: "restart_server",
      label: "Restart server",
      mode: "manual",
      command: `folderforge chatgpt start --project ${project}`,
      explanation:
        "Restarting this process from its own dashboard would interrupt the response.",
    },
    restart_tunnel: {
      id: "restart_tunnel",
      label: "Restart tunnel",
      mode: "manual",
      command: `folderforge chatgpt repair --project ${project}`,
      explanation:
        "A temporary tunnel restart can change the MCP resource URL and requires a new ChatGPT DCR client.",
    },
    repair_auth0: {
      id: "repair_auth0",
      label: "Repair Auth0",
      mode: "automatic",
    },
    enable_login_connection: {
      id: "enable_login_connection",
      label: "Enable login connection",
      mode: "automatic",
    },
    repair_user_grant: {
      id: "repair_user_grant",
      label: "Repair user grant",
      mode: "automatic",
    },
    wait_for_dcr_client: {
      id: "wait_for_dcr_client",
      label: "Wait for DCR client",
      mode: "automatic",
      explanation: "Click Connect in ChatGPT while this action is running.",
    },
    rerun_verification: {
      id: "rerun_verification",
      label: "Re-run verification",
      mode: "automatic",
    },
    copy_mcp_url: {
      id: "copy_mcp_url",
      label: "Copy MCP URL",
      mode: "client",
    },
  };
  return (
    definitions[action] ?? {
      id: action,
      label: action.replace(/_/g, " "),
      mode: "manual",
    }
  );
}

function lifecycleSummary(snapshot: ChatGptLifecycleSnapshot): string {
  if (snapshot.overall === "connected")
    return "ChatGPT is authenticated and MCP is ready.";
  if (snapshot.state === "READY_TO_COMPLETE_LOGIN") {
    return "OAuth is ready. Return to ChatGPT and complete sign-in.";
  }
  if (snapshot.state === "WAITING_FOR_CHATGPT_CLIENT") {
    return "Waiting for ChatGPT to register an OAuth client.";
  }
  if (snapshot.overall === "stopped")
    return "The local server or public tunnel is stopped.";
  return "The ChatGPT connection needs attention. Review diagnostics and run the suggested repair.";
}

function unconfiguredChatGptStatus(
  container: Container,
): DashboardChatGptStatus {
  const snapshot = deriveChatGptLifecycle({
    receiptExists: false,
    serverAlive: false,
    tunnelRequired: false,
    tunnelAlive: false,
    checks: {},
  });
  return {
    configured: false,
    status: "unconfigured",
    state: snapshot.state,
    summary: "ChatGPT is not configured. Run `folderforge connect chatgpt`.",
    timeline: snapshot.timeline,
    diagnostics: snapshot.diagnostics,
    actions: [
      {
        id: "connect_chatgpt",
        label: "Connect ChatGPT",
        mode: "manual",
        command: `folderforge connect chatgpt --project ${quoteCliPath(container.projectRoot())}`,
      },
    ],
    configuration: {
      projectRoot: container.projectRoot(),
      policyMode: container.policy.getMode(),
      enabledAdapters: Object.entries(container.config.adapters)
        .filter(([, value]) => Boolean(value?.enabled))
        .map(([name]) => name),
    },
    lastChecked: new Date().toISOString(),
  };
}

function chatGptStatus(container: Container): DashboardChatGptStatus {
  const receiptPath = join(
    container.projectRoot(),
    ".folderforge",
    "chatgpt-connection.json",
  );
  if (!existsSync(receiptPath)) return unconfiguredChatGptStatus(container);
  const receipt = readConnectionReceipt(receiptPath);
  const serverAlive = processAlive(receipt.processes.serverPid);
  const tunnelAlive =
    receipt.connectivity.kind !== "cloudflared-quick" ||
    processAlive(receipt.processes.tunnelPid);
  const snapshot = refreshChatGptLifecycle(receipt, serverAlive, tunnelAlive);
  const actionIds = new Set(snapshot.actions);
  actionIds.add("copy_mcp_url");
  if (serverAlive) actionIds.add("restart_server");
  const localPort = (() => {
    try {
      return Number(new URL(receipt.connectivity.localUrl).port) || null;
    } catch {
      return null;
    }
  })();
  return redactSensitive({
    configured: true,
    status: snapshot.overall,
    state: snapshot.state,
    summary: lifecycleSummary(snapshot),
    mcpUrl: receipt.mcpUrl,
    timeline: snapshot.timeline,
    diagnostics: snapshot.diagnostics,
    actions: [...actionIds].map((action) =>
      actionDescriptor(action, receipt.projectRoot),
    ),
    configuration: {
      projectRoot: receipt.projectRoot,
      port: localPort,
      publicUrl: receipt.connectivity.publicUrl,
      tenant: receipt.tenant,
      profile: receipt.runtime?.profile ?? null,
      policyMode: receipt.runtime?.policyMode ?? container.policy.getMode(),
      resourcePolicy: receipt.runtime?.dcrClientPolicy ?? null,
      toolPreset: receipt.runtime?.toolsPreset ?? null,
      enabledAdapters: receipt.runtime?.adapters ?? [],
      loginConnections: receipt.runtime?.loginConnections ?? [],
      registration: receipt.registration,
      connectivity: receipt.connectivity.kind,
    },
    lastChecked: snapshot.updatedAt,
  });
}

function boundedLogTail(
  path: string,
  projectRoot: string,
  limit: number,
): string[] {
  const root = resolve(projectRoot);
  const target = resolve(path);
  if (target !== root && !target.startsWith(`${root}${sep}`)) {
    throw new Error("Log path is outside the active project boundary.");
  }
  if (!existsSync(target)) return [];
  const size = statSync(target).size;
  const bytesToRead = Math.min(size, 256 * 1024);
  const buffer = Buffer.alloc(bytesToRead);
  const fd = openSync(target, "r");
  try {
    readSync(fd, buffer, 0, bytesToRead, Math.max(0, size - bytesToRead));
  } finally {
    closeSync(fd);
  }
  return buffer
    .toString("utf8")
    .split("\n")
    .slice(size > bytesToRead ? 1 : 0)
    .filter(Boolean)
    .slice(-limit)
    .map(redactSensitiveText);
}

async function runChatGptDashboardAction(
  action: string,
  container: Container,
): Promise<{ status: number; body: Record<string, unknown> }> {
  const root = container.projectRoot();
  if (
    action === "start_server" ||
    action === "restart_server" ||
    action === "restart_tunnel"
  ) {
    const descriptor = actionDescriptor(action, root);
    return {
      status: 202,
      body: {
        accepted: false,
        requiresTerminal: true,
        action: descriptor,
      },
    };
  }
  const commandArgs: Record<string, string[]> = {
    rerun_verification: ["status", "--project", root, "--json"],
    repair_auth0: [
      "repair",
      "--project",
      root,
      "--no-start",
      "--no-wait",
      "--json",
    ],
    enable_login_connection: [
      "repair",
      "--project",
      root,
      "--no-start",
      "--no-wait",
      "--json",
    ],
    repair_user_grant: [
      "repair",
      "--project",
      root,
      "--no-start",
      "--no-wait",
      "--json",
    ],
    wait_for_dcr_client: [
      "repair",
      "--project",
      root,
      "--no-start",
      "--wait",
      "--wait-timeout",
      "60",
      "--poll-interval",
      "2",
      "--json",
    ],
  };
  const args = commandArgs[action];
  if (!args) {
    return { status: 404, body: { error: "unknown_chatgpt_action", action } };
  }
  const result = await executeChatGptCli(args, { cwd: root });
  return {
    status: result.exitCode === 0 ? 200 : 409,
    body: redactSensitive({
      ok: result.exitCode === 0,
      output: result.output,
      status: result.receipt?.lifecycleSnapshot ?? null,
    }),
  };
}

async function runOperatorTool(
  registry: ToolRegistry,
  container: Container,
  principal: ToolPrincipal,
  tool: string,
  args: Record<string, unknown>,
) {
  const actionPrincipal: ToolPrincipal = {
    ...principal,
    id: `${principal.id}:operator-action`,
    roles: [...new Set([...(principal.roles ?? [principal.role]), MISSION_CONTROL_OPERATOR_ROLE])],
    sessionId: `${principal.id}:dashboard-session`,
  };
  let result = await registry.call(tool, args, { principal: actionPrincipal });
  if (result.approvalId) {
    const approval = container.policy.approvals.approve(
      result.approvalId,
      'once',
      principal.id,
    );
    container.audit.record({
      type: 'approval_resolved',
      summary: `operator approve ${result.approvalId} (once)`,
      detail: {
        approvalId: result.approvalId,
        approverId: principal.id,
        requesterId: approval?.requesterId,
        binding: approval?.binding,
      },
    });
    result = await registry.call(tool, args, { principal: actionPrincipal });
  }
  return result;
}

function missionControlSnapshot(
  container: Container,
  registry: ToolRegistry,
  principal: ToolPrincipal,
): Record<string, unknown> {
  const tasks = container.workflows.list(principal, 100);
  const capsules = container.capsules.list();
  const isolations = container.isolation.list();
  const processes = container.processes.list();
  const approvals = container.policy.approvals.pending();
  const verifications = container.verifications.list(principal, 100);
  const activeCalls = registry.listActiveCalls();
  const recentActivity = container.audit
    .recent(100)
    .filter((event) =>
      [
        'tool_call',
        'tool_result',
        'tool_error',
        'policy_deny',
        'process_event',
        'task_event',
      ].includes(event.type),
    )
    .slice(0, 50);
  const activeCapsules = capsules.filter(
    (capsule) => !capsule.revokedAt && Date.parse(capsule.expiresAt) > Date.now(),
  );
  const proofPackCount = tasks.reduce(
    (count, task) => count + task.proofPacks.length,
    0,
  );
  return redactSensitive({
    generatedAt: new Date().toISOString(),
    control: container.missionControl.describe(),
    workspace: {
      root: container.projectRoot(),
      active: container.workspace.getActive(),
      startupError: container.workspaceStartupError,
    },
    summary: {
      activeCalls: activeCalls.length,
      authorizedSessions: activeCapsules.length,
      tasks: tasks.length,
      runningTasks: tasks.filter((task) => task.state === 'running').length,
      pausedTasks: tasks.filter((task) => task.state === 'paused').length,
      pendingApprovals: approvals.length,
      managedProcesses: processes.length,
      activeProcesses: processes.filter((process) => process.status === 'running').length,
      isolations: isolations.length,
      proofPacks: proofPackCount,
      verificationRuns: verifications.length,
      runningVerifications: verifications.filter((run) => run.state === 'running').length,
      verificationIssues: verifications.filter(
        (run) => run.overall === 'failed' || run.overall === 'unavailable',
      ).length,
    },
    activeCalls,
    authorizedSessions: activeCapsules.map((capsule) => ({
      id: capsule.id,
      principalId: capsule.principalId,
      clientId: capsule.clientId,
      sessionId: capsule.sessionId,
      taskId: capsule.taskId,
      profile: capsule.profile,
      workspaceRoot: capsule.workspaceRoot,
      expiresAt: capsule.expiresAt,
      usage: capsule.usage,
    })),
    tasks,
    approvals,
    verifications,
    processes,
    isolations,
    recentActivity,
  }) as Record<string, unknown>;
}

async function handle(
  req: IncomingMessage,
  res: ServerResponse,
  container: Container,
  registry: ToolRegistry,
  principal: ToolPrincipal,
): Promise<void> {
  const method = req.method ?? "GET";
  const url = new URL(req.url ?? "/", "http://localhost");
  const path = url.pathname;

  if (method === "GET" && path === "/app") {
    // The canonical mount has a trailing slash so the SPA's relative assets
    // resolve under /app/. Preserve the query string (?token= flows through).
    res.writeHead(308, { location: `/app/${url.search}` });
    res.end();
    return;
  }

  if (method === "GET" && (path === "/app/" || path.startsWith("/app/"))) {
    return serveMissionControlApp(res, path);
  }

  // Directory browsing for the SPA folder picker, restricted to the widest
  // directory the operator lets this control plane govern.
  if (method === "POST" && path === "/fs/browse") {
    const body = await readJsonBody(req);
    const roots = fsAllowedRoots(container);
    const target = resolve(
      typeof body?.path === "string" && body.path.length > 0 ? body.path : roots[0]!,
    );
    if (!roots.some((r) => isWithinDir(r, target))) {
      return sendJson(res, 403, {
        error: "forbidden",
        message: `Browsing is restricted to the allowed roots: ${roots.join(", ")}`,
      });
    }
    let entries;
    try {
      entries = readdirSync(target, { withFileTypes: true });
    } catch {
      return sendJson(res, 404, { error: "not_found", message: "Not a readable directory." });
    }
    const directories = entries
      .filter((e) => {
        if (!e.isDirectory()) return false;
        if (e.name === "node_modules" || e.name.startsWith(".")) return false;
        try {
          return !lstatSync(join(target, e.name)).isSymbolicLink();
        } catch {
          return false;
        }
      })
      .map((e) => ({ name: e.name, path: join(target, e.name) }))
      .sort((a, b) => a.name.localeCompare(b.name))
      .slice(0, 200);
    return sendJson(res, 200, {
      path: target,
      parent: dirname(target),
      canGoUp: roots.some((r) => isWithinDir(r, dirname(target))),
      home: homedir(),
      root: roots.find((r) => isWithinDir(r, target)) ?? roots[0],
      directories,
    });
  }

  if (method === "POST" && path === "/fs/mkdir") {
    const body = await readJsonBody(req);
    const roots = fsAllowedRoots(container);
    const parent = resolve(String(body?.path ?? ""));
    const name = String(body?.name ?? "").trim();
    if (!name || name.includes("/") || name.includes("\\") || name === "." || name === "..") {
      return sendJson(res, 400, { error: "invalid_request", message: "Invalid folder name." });
    }
    const target = join(parent, name);
    if (!roots.some((r) => isWithinDir(r, target))) {
      return sendJson(res, 403, {
        error: "forbidden",
        message: `Creating folders is restricted to the allowed roots: ${roots.join(", ")}`,
      });
    }
    try {
      mkdirSync(target, { recursive: true });
    } catch (err) {
      return sendJson(res, 409, { error: "mkdir_failed", message: String(err) });
    }
    container.audit.record({
      type: "dashboard_action",
      summary: `mkdir ${target} (principal ${principal.id})`,
    });
    return sendJson(res, 200, { ok: true, path: target });
  }

  if (method === "GET" && (path === "/" || path === "/index.html")) {
    // The Mission Control SPA is the primary UI: root goes straight to it.
    res.writeHead(308, { location: `/app/${url.search}` });
    res.end();
    return;
  }

  if (method === "GET" && path === "/status") {
    const active = container.workspace.getActive();
    return sendJson(res, 200, {
      server: {
        name: container.config.server.name,
        transport: container.config.server.transport,
        version: readFolderForgeVersion(),
      },
      workspace: {
        active: Boolean(active),
        projectRoot: container.projectRoot(),
        name: active?.name ?? null,
        languageHints: active?.languageHints ?? [],
        startupError: container.workspaceStartupError,
        allowedDirectories: container.config.workspace.allowedDirectories,
        browsePoint: fsBrowsePoint(container),
      },
      policy: container.policy.describe(),
      capsules: container.capsules.describe(),
      isolation: container.isolation.describe(),
      missionControl: container.missionControl.describe(),
      tools: {
        active: registry.listActive().length,
        total: registry.listAll().length,
      },
    });
  }

  if (method === "GET" && path === "/mission-control") {
    return sendJson(
      res,
      200,
      missionControlSnapshot(container, registry, principal),
    );
  }

  if (method === "POST" && path === "/mission-control/write-freeze") {
    const body = await readJsonBody(req);
    if (typeof body?.enabled !== 'boolean') {
      return sendJson(res, 400, {
        error: 'invalid_write_freeze',
        message: 'enabled must be a boolean.',
      });
    }
    const before = container.missionControl.describe();
    const control = container.missionControl.setWriteFreeze(
      body.enabled,
      principal.id,
    );
    container.audit.record({
      type: 'policy_change',
      summary: body.enabled
        ? 'mission_control_write_freeze_enabled'
        : 'mission_control_write_freeze_disabled',
      detail: { actorId: principal.id, before, after: control },
    });
    return sendJson(res, 200, { control });
  }

  const missionTaskMatch = /^\/mission-control\/tasks\/([^/]+)\/(pause|cancel)$/.exec(path);
  if (method === "POST" && missionTaskMatch) {
    const id = decodeURIComponent(missionTaskMatch[1]!);
    const action = missionTaskMatch[2]!;
    const body = await readJsonBody(req);
    const result = await runOperatorTool(
      registry,
      container,
      principal,
      action === 'pause' ? 'workflow_pause' : 'workflow_cancel',
      {
        id,
        ...(action === 'pause' && typeof body?.reason === 'string'
          ? { reason: body.reason }
          : {}),
      },
    );
    return sendJson(res, result.ok ? 200 : 409, result);
  }

  const missionProcessMatch = /^\/mission-control\/processes\/([^/]+)\/(stop|kill)$/.exec(path);
  if (method === "POST" && missionProcessMatch) {
    const sessionId = decodeURIComponent(missionProcessMatch[1]!);
    const action = missionProcessMatch[2]!;
    const result = await runOperatorTool(
      registry,
      container,
      principal,
      action === 'stop' ? 'process_stop' : 'process_kill',
      { sessionId },
    );
    return sendJson(res, result.ok ? 200 : 409, result);
  }

  const missionCapsuleMatch = /^\/mission-control\/capsules\/([^/]+)\/revoke$/.exec(path);
  if (method === "POST" && missionCapsuleMatch) {
    const id = decodeURIComponent(missionCapsuleMatch[1]!);
    const capsule = container.capsules.revoke(id, principal.id);
    if (!capsule) return sendJson(res, 404, { error: 'capsule_not_found', id });
    container.audit.record({
      type: 'policy_change',
      summary: `mission_control_capsule_revoked:${id}`,
      detail: { actorId: principal.id, capsuleId: id },
    });
    return sendJson(res, 200, { capsule });
  }

  const missionIsolationMatch = /^\/mission-control\/isolations\/([^/]+)\/(rollback|discard)$/.exec(path);
  if (method === "POST" && missionIsolationMatch) {
    const id = decodeURIComponent(missionIsolationMatch[1]!);
    const action = missionIsolationMatch[2]!;
    const result = await runOperatorTool(
      registry,
      container,
      principal,
      action === 'rollback' ? 'isolation_rollback' : 'isolation_discard',
      { id },
    );
    return sendJson(res, result.ok ? 200 : 409, result);
  }

  if (method === "GET" && path === "/fleet") {
    return sendJson(res, 200, { instances: container.fleet.list() });
  }

  if (method === "POST" && path === "/fleet") {
    const body = await readJsonBody(req);
    const projectPath =
      typeof body?.projectPath === 'string' ? body.projectPath.trim() : '';
    if (!projectPath) {
      return sendJson(res, 400, {
        error: 'invalid_fleet_create',
        message: 'projectPath (string) is required.',
      });
    }
    const result = await runOperatorTool(
      registry,
      container,
      principal,
      'provision_create',
      {
        projectPath,
        ...(typeof body?.name === 'string' ? { name: body.name } : {}),
        ...(typeof body?.toolsPreset === 'string'
          ? { toolsPreset: body.toolsPreset }
          : {}),
        ...(typeof body?.policyMode === 'string'
          ? { policyMode: body.policyMode }
          : {}),
      },
    );
    return sendJson(res, result.ok ? 201 : 409, result);
  }

  const fleetLifecycleMatch = /^\/fleet\/([^/]+)\/(start|stop|restart)$/.exec(path);
  if (method === "POST" && fleetLifecycleMatch) {
    const id = decodeURIComponent(fleetLifecycleMatch[1]!);
    const action = fleetLifecycleMatch[2]!;
    const tool =
      action === 'start'
        ? 'provision_start'
        : action === 'stop'
          ? 'provision_stop'
          : 'provision_restart';
    const result = await runOperatorTool(registry, container, principal, tool, { id });
    return sendJson(res, result.ok ? 200 : 409, result);
  }

  const fleetAutoRestartMatch = /^\/fleet\/([^/]+)\/auto-restart$/.exec(path);
  if (method === "POST" && fleetAutoRestartMatch) {
    const id = decodeURIComponent(fleetAutoRestartMatch[1]!);
    const body = await readJsonBody(req);
    if (typeof body?.enabled !== 'boolean') {
      return sendJson(res, 400, {
        error: 'invalid_auto_restart',
        message: 'enabled must be a boolean.',
      });
    }
    const result = await runOperatorTool(registry, container, principal, 'provision_update', {
      id,
      autoRestart: body.enabled,
    });
    return sendJson(res, result.ok ? 200 : 409, result);
  }

  const fleetPresetMatch = /^\/fleet\/([^/]+)\/preset$/.exec(path);
  if (method === "POST" && fleetPresetMatch) {
    const id = decodeURIComponent(fleetPresetMatch[1]!);
    const body = await readJsonBody(req);
    if (typeof body?.toolsPreset !== 'string' || body.toolsPreset.length === 0) {
      return sendJson(res, 400, {
        error: 'invalid_preset',
        message: 'toolsPreset must be one of: vibe, vibe-lite, readonly, full, godot.',
      });
    }
    const result = await runOperatorTool(registry, container, principal, 'provision_update', {
      id,
      toolsPreset: body.toolsPreset,
    });
    return sendJson(res, result.ok ? 200 : 409, result);
  }

  if (method === "GET" && path === "/plugins") {
    const result = await runOperatorTool(registry, container, principal, 'plugin_list', {});
    return sendJson(res, result.ok ? 200 : 409, result.ok ? result.data : result);
  }

  if (method === "GET" && path === "/marketplace") {
    const result = await runOperatorTool(registry, container, principal, 'marketplace_list', {});
    return sendJson(res, result.ok ? 200 : 409, result.ok ? result.data : result);
  }

  const pluginLifecycleMatch = /^\/plugins\/([^/]+)\/(enable|disable)$/.exec(path);
  if (method === "POST" && pluginLifecycleMatch) {
    const id = decodeURIComponent(pluginLifecycleMatch[1]!);
    const action = pluginLifecycleMatch[2]!;
    const result = await runOperatorTool(
      registry,
      container,
      principal,
      action === 'enable' ? 'plugin_enable' : 'plugin_disable',
      { id },
    );
    return sendJson(res, result.ok ? 200 : 409, result);
  }

  if (method === "GET" && path === "/tools") {
    const tools = registry.listAll().map((tool) => ({
      name: tool.name,
      group: tool.group,
      risk: tool.risk,
      mutates: tool.mutates,
      title: tool.annotations?.title ?? tool.name,
      description: tool.description,
    }));
    const presets: Record<string, { groups: string[]; toolCount: number }> = {};
    for (const [preset, groups] of Object.entries(GROUP_PRESETS)) {
      const active = resolveActiveTools(registry, { preset });
      presets[preset] = {
        groups,
        toolCount: active === null ? tools.length : active.length,
      };
    }
    return sendJson(res, 200, { tools, presets });
  }

  if (method === "GET" && path === "/workspaces") {
    const result = await runOperatorTool(registry, container, principal, 'workspace_list', {});
    return sendJson(res, result.ok ? 200 : 409, result.ok ? result.data : result);
  }

  if (method === "POST" && path === "/workspaces/switch") {
    const body = await readJsonBody(req);
    if (typeof body?.path !== 'string' || body.path.length === 0) {
      return sendJson(res, 400, {
        error: 'invalid_workspace',
        message: 'path must be a non-empty string.',
      });
    }
    const result = await runOperatorTool(registry, container, principal, 'workspace_switch', {
      path: body.path,
    });
    return sendJson(res, result.ok ? 200 : 409, result);
  }

  if (method === "POST" && path === "/workspaces/activate") {
    const body = await readJsonBody(req);
    if (typeof body?.path !== 'string' || body.path.length === 0) {
      return sendJson(res, 400, {
        error: 'invalid_workspace',
        message: 'path must be a non-empty string.',
      });
    }
    const result = await runOperatorTool(registry, container, principal, 'workspace_activate', {
      path: body.path,
    });
    return sendJson(res, result.ok ? 200 : 409, result);
  }

  if (method === "GET" && path === "/cloudflare/status") {
    return sendJson(res, 200, maskedCloudflareConfig(container.projectRoot()));
  }

  if (method === "POST" && path === "/cloudflare/config") {
    const body = await readJsonBody(req);
    const apiToken = typeof body?.apiToken === "string" ? body.apiToken.trim() : "";
    const accountId = typeof body?.accountId === "string" ? body.accountId.trim() : "";
    const domain = typeof body?.domain === "string" ? body.domain.trim().toLowerCase() : "";
    const DOMAIN_RE = /^(?=.{1,253}$)([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}$/;
    if (!apiToken || !accountId || !DOMAIN_RE.test(domain)) {
      return sendJson(res, 400, {
        error: "invalid_cloudflare_config",
        message: "apiToken, accountId and a valid domain (e.g. example.com) are required.",
      });
    }
    const client = makeCloudflareClient(apiToken);
    try {
      await client.verifyToken();
      const zoneId = await client.resolveZoneId(domain);
      saveCloudflareConfig(container.projectRoot(), {
        accountId,
        zoneId,
        domain,
        apiToken,
        linkedAt: new Date().toISOString(),
      });
    } catch (error) {
      return sendJson(res, 502, {
        error: "cloudflare_rejected",
        message: error instanceof Error ? error.message : String(error),
      });
    }
    container.audit.record({
      type: "dashboard_action",
      summary: "cloudflare linked domain=" + domain + " account=" + accountId + " (principal " + principal.id + ")",
    });
    return sendJson(res, 200, maskedCloudflareConfig(container.projectRoot()));
  }

  if (method === "DELETE" && path === "/cloudflare/config") {
    clearCloudflareConfig(container.projectRoot());
    container.audit.record({
      type: "dashboard_action",
      summary: "cloudflare unlinked (principal " + principal.id + ")",
    });
    return sendJson(res, 200, { ok: true });
  }

  if (method === "GET" && path === "/tunnels") {
    const result = await runOperatorTool(registry, container, principal, 'tunnel_list', {});
    return sendJson(res, result.ok ? 200 : 409, result.ok ? result.data : result);
  }

  if (method === "POST" && path === "/tunnels") {
    const body = await readJsonBody(req);
    if (typeof body?.targetPort !== 'number' || !Number.isInteger(body.targetPort)) {
      return sendJson(res, 400, {
        error: 'invalid_tunnel',
        message: 'targetPort must be an integer port (1024-65535).',
      });
    }
    const result = await runOperatorTool(registry, container, principal, 'tunnel_start', {
      targetPort: body.targetPort,
    });
    return sendJson(res, result.ok ? 201 : 409, result);
  }

  const tunnelStopMatch = /^\/tunnels\/([^/]+)\/stop$/.exec(path);
  if (method === "POST" && tunnelStopMatch) {
    const id = decodeURIComponent(tunnelStopMatch[1]!);
    const body = await readJsonBody(req);
    if (body?.cleanup === true) {
      try {
        const record = await container.tunnels.destroy(id);
        container.audit.record({
          type: "dashboard_action",
          summary: "tunnel " + id + " stopped + cloudflare cleanup (principal " + principal.id + ")",
        });
        return sendJson(res, 200, { ok: true, data: record });
      } catch (error) {
        return sendJson(res, 409, {
          error: "unknown_tunnel",
          message: error instanceof Error ? error.message : String(error),
        });
      }
    }
    const result = await runOperatorTool(registry, container, principal, 'tunnel_stop', { id });
    return sendJson(res, result.ok ? 200 : 409, result);
  }

  if (method === "GET" && path === "/chatgpt/status") {
    return sendJson(res, 200, chatGptStatus(container));
  }

  if (method === "GET" && path === "/chatgpt/logs") {
    const receiptPath = join(
      container.projectRoot(),
      ".folderforge",
      "chatgpt-connection.json",
    );
    if (!existsSync(receiptPath)) {
      return sendJson(res, 404, { error: "chatgpt_not_configured" });
    }
    const subsystem = url.searchParams.get("subsystem") ?? "server";
    if (subsystem !== "server" && subsystem !== "tunnel") {
      return sendJson(res, 400, { error: "invalid_log_subsystem", subsystem });
    }
    const receipt = readConnectionReceipt(receiptPath);
    const logPath =
      subsystem === "server"
        ? receipt.processes.serverLog
        : receipt.processes.tunnelLog;
    const limit = clampInt(url.searchParams.get("limit"), 120, 1, 500);
    const lines = logPath
      ? boundedLogTail(logPath, receipt.projectRoot, limit)
      : [];
    return sendJson(res, 200, { subsystem, lines });
  }

  const chatGptActionMatch = /^\/chatgpt\/actions\/([^/]+)$/.exec(path);
  if (method === "POST" && chatGptActionMatch) {
    const action = decodeURIComponent(chatGptActionMatch[1]!);
    const result = await runChatGptDashboardAction(action, container);
    container.audit.record({
      type: "process_event",
      summary: `chatgpt_dashboard_action:${action}`,
      ok: result.status < 400,
      detail: { actorId: principal.id, action, status: result.status },
    });
    return sendJson(res, result.status, result.body);
  }

  if (method === "GET" && path === "/audit") {
    const limit = clampInt(url.searchParams.get("limit"), 50, 1, 500);
    return sendJson(
      res,
      200,
      redactSensitive({ entries: container.audit.recent(limit) }),
    );
  }

  if (method === "GET" && path === "/processes") {
    return sendJson(res, 200, { processes: container.processes.list() });
  }

  if (method === "GET" && path === "/isolations") {
    return sendJson(res, 200, {
      ...container.isolation.describe(),
      isolations: container.isolation.list(),
    });
  }

  if (method === "POST" && path === "/isolations") {
    const body = await readJsonBody(req);
    const result = await runOperatorTool(registry, container, principal, 'isolation_create', {
      taskId: String(body?.taskId ?? ''),
      baseRef: String(body?.baseRef ?? 'HEAD'),
    });
    return sendJson(res, result.ok ? 201 : 409, result);
  }

  const isolationReadMatch = /^\/isolations\/([^/]+)\/(status|diff)$/.exec(path);
  if (method === "GET" && isolationReadMatch) {
    const id = decodeURIComponent(isolationReadMatch[1]!);
    const tool = isolationReadMatch[2] === 'diff' ? 'isolation_diff' : 'isolation_status';
    const result = await runOperatorTool(registry, container, principal, tool, { id });
    return sendJson(res, result.ok ? 200 : 409, result);
  }

  const isolationActionMatch = /^\/isolations\/([^/]+)\/(apply|rollback|discard)$/.exec(path);
  if (method === "POST" && isolationActionMatch) {
    const id = decodeURIComponent(isolationActionMatch[1]!);
    const action = isolationActionMatch[2];
    const tool = action === 'apply'
      ? 'isolation_apply'
      : action === 'rollback'
        ? 'isolation_rollback'
        : 'isolation_discard';
    const result = await runOperatorTool(registry, container, principal, tool, { id });
    return sendJson(res, result.ok ? 200 : 409, result);
  }

  const fleetPolicyMatch = /^\/fleet\/([^/]+)\/policy$/.exec(path);
  if (method === "POST" && fleetPolicyMatch) {
    const id = decodeURIComponent(fleetPolicyMatch[1]!);
    const body = await readJsonBody(req);
    const result = await runOperatorTool(registry, container, principal, "provision_update", {
      id,
      policyMode: String(body?.policyMode ?? ""),
    });
    return sendJson(res, result.ok ? 200 : 409, result);
  }

  const fleetRotateMatch = /^\/fleet\/([^/]+)\/rotate-token$/.exec(path);
  if (method === "POST" && fleetRotateMatch) {
    const id = decodeURIComponent(fleetRotateMatch[1]!);
    const result = await runOperatorTool(
      registry,
      container,
      principal,
      "provision_rotate_token",
      { id },
    );
    return sendJson(res, result.ok ? 200 : 409, result);
  }

  const fleetTunnelMatch = /^\/fleet\/([^/]+)\/tunnel$/.exec(path);
  if (method === "POST" && fleetTunnelMatch) {
    const id = decodeURIComponent(fleetTunnelMatch[1]!);
    const instance = container.fleet.get(id);
    if (!instance || instance.state !== "running") {
      return sendJson(res, 409, {
        error: "not_running",
        message: `Instance ${id} is not running.`,
      });
    }
    const body = await readJsonBody(req);
    if (body && typeof body.hostname === "string" && body.hostname.trim()) {
      try {
        const record = await container.tunnels.startNamed({
          targetPort: instance.port,
          hostname: body.hostname,
          actor: principal.id,
        });
        container.audit.record({
          type: "dashboard_action",
          summary: "named tunnel " + record.id + " " + (record.hostname ?? "") + " -> :" + instance.port + " (principal " + principal.id + ")",
        });
        return sendJson(res, 200, { ok: true, data: record });
      } catch (error) {
        return sendJson(res, 409, {
          error: "named_tunnel_failed",
          message: error instanceof Error ? error.message : String(error),
        });
      }
    }
    const result = await runOperatorTool(registry, container, principal, "tunnel_start", {
      targetPort: instance.port,
    });
    return sendJson(res, result.ok ? 200 : 409, result);
  }

  const fleetLogsMatch = /^\/fleet\/([^/]+)\/logs$/.exec(path);
  if (method === "GET" && fleetLogsMatch) {
    const id = decodeURIComponent(fleetLogsMatch[1]!);
    let instance;
    try {
      instance = container.fleet.get(id);
    } catch {
      instance = undefined;
    }
    if (!instance) {
      return sendJson(res, 404, { error: "unknown_instance", message: "Unknown instance: " + id });
    }
    const sessionId = instance.sessionId;
    if (!sessionId || !container.processes.isManaged(sessionId)) {
      return sendJson(res, 409, {
        error: "no_logs",
        message: "No live process session for this instance (start it first; sessions reset when the plane restarts).",
      });
    }
    const peeked = container.processes.peek(sessionId);
    return sendJson(res, 200, { id, status: peeked.status, output: peeked.output });
  }

  if (method === "GET" && path === "/approvals") {
    return sendJson(res, 200, {
      pending: container.policy.approvals.pending(),
      all: container.policy.approvals.all(),
    });
  }

  if (method === "GET" && path === "/capsules") {
    return sendJson(res, 200, {
      ...container.capsules.describe(),
      capsules: container.capsules.list(),
    });
  }

  if (method === "POST" && path === "/capsules") {
    const body = await readJsonBody(req);
    try {
      const capsule = container.capsules.create({
        workspaceRoot: String(body?.workspaceRoot ?? container.projectRoot()),
        principalId: String(body?.principalId ?? ""),
        profile: String(body?.profile ?? "") as import('../capsule/workspace-capsule-manager.js').PermissionProfile,
        ...(body?.ttlMs !== undefined ? { ttlMs: Number(body.ttlMs) } : {}),
        ...(typeof body?.sessionId === "string" ? { sessionId: body.sessionId } : {}),
        ...(typeof body?.clientId === "string" ? { clientId: body.clientId } : {}),
        ...(typeof body?.taskId === "string" ? { taskId: body.taskId } : {}),
        ...(Array.isArray(body?.grantedScopes)
          ? { grantedScopes: body.grantedScopes.map(String) }
          : {}),
        ...(typeof body?.isolation === "string"
          ? { isolation: body.isolation as import('../capsule/workspace-capsule-manager.js').CapsuleIsolation }
          : {}),
        ...(typeof body?.networkPolicy === "string"
          ? { networkPolicy: body.networkPolicy as import('../capsule/workspace-capsule-manager.js').CapsuleNetworkPolicy }
          : {}),
        ...(body?.limits && typeof body.limits === "object"
          ? { limits: body.limits as Partial<import('../capsule/workspace-capsule-manager.js').CapsuleLimits> }
          : {}),
        ...(typeof body?.evidenceDestination === "string"
          ? { evidenceDestination: body.evidenceDestination }
          : {}),
        ...(typeof body?.clientCompatibility === "string"
          ? { clientCompatibility: body.clientCompatibility as import('../capsule/workspace-capsule-manager.js').ClientCompatibilityProfile }
          : {}),
      });
      container.audit.record({
        type: "policy_change",
        summary: `capsule_created:${capsule.id}`,
        detail: {
          actorId: principal.id,
          capsuleId: capsule.id,
          principalId: capsule.principalId,
          profile: capsule.profile,
          workspaceId: capsule.workspaceId,
        },
      });
      return sendJson(res, 201, { capsule });
    } catch (error) {
      return sendJson(res, 400, {
        error: "invalid_capsule",
        message: error instanceof Error ? error.message : String(error),
      });
    }
  }

  const capsuleMatch = /^\/capsules\/([^/]+)\/revoke$/.exec(path);
  if (method === "POST" && capsuleMatch) {
    const id = decodeURIComponent(capsuleMatch[1]!);
    const capsule = container.capsules.revoke(id, principal.id);
    if (!capsule) return sendJson(res, 404, { error: "capsule_not_found", id });
    container.audit.record({
      type: "policy_change",
      summary: `capsule_revoked:${id}`,
      detail: { actorId: principal.id, capsuleId: id },
    });
    return sendJson(res, 200, { capsule });
  }

  // POST /approvals/:id/approve | /approvals/:id/deny
  const approvalMatch = /^\/approvals\/([^/]+)\/(approve|deny)$/.exec(path);
  if (method === "POST" && approvalMatch) {
    const id = approvalMatch[1]!;
    const action = approvalMatch[2]!;
    const body = await readJsonBody(req);
    let result;
    try {
      if (action === "approve") {
        const scope = body?.scope === "session" ? "session" : "once";
        result = container.policy.approvals.approve(id, scope, principal.id);
      } else {
        result = container.policy.approvals.deny(id, principal.id);
      }
    } catch (error) {
      if (error instanceof ApprovalResolutionError) {
        return sendJson(res, 409, {
          error: error.code,
          message: error.message,
          id,
        });
      }
      throw error;
    }
    if (!result) {
      return sendJson(res, 404, { error: "approval_not_found", id });
    }
    container.audit.record({
      type: "approval_resolved",
      tool: result.tool,
      risk: result.risk,
      summary: `${action} (${result.state})`,
      detail: { approvalId: id, approverId: principal.id },
    });
    return sendJson(res, 200, { approval: result });
  }

  if (method === "POST" && path === "/policy/mode") {
    const body = await readJsonBody(req);
    const mode = String(body?.mode ?? "") as PolicyMode;
    if (!["readonly", "safe", "dev", "danger"].includes(mode)) {
      return sendJson(res, 400, { error: "invalid_policy_mode", mode });
    }
    try {
      container.missionControl.setPolicyMode(mode, principal.id);
    } catch (error) {
      return sendJson(res, 409, {
        error: 'policy_mode_blocked',
        message: error instanceof Error ? error.message : String(error),
      });
    }
    container.audit.record({
      type: "policy_change",
      summary: `mode=${mode}`,
      detail: { actorId: principal.id, mode },
    });
    return sendJson(res, 200, { mode });
  }

  sendJson(res, 404, { error: "not_found", path });
}


function sendJson(res: ServerResponse, status: number, body: unknown): void {
  res.writeHead(status, { "content-type": "application/json; charset=utf-8" });
  res.end(JSON.stringify(body, null, 2));
}

async function readJsonBody(
  req: IncomingMessage,
): Promise<Record<string, unknown> | null> {
  return new Promise((resolveBody) => {
    let raw = "";
    req.on("data", (chunk) => {
      raw += chunk;
      if (raw.length > 1_000_000) req.destroy();
    });
    req.on("end", () => {
      if (!raw.trim()) return resolveBody(null);
      try {
        resolveBody(JSON.parse(raw) as Record<string, unknown>);
      } catch {
        resolveBody(null);
      }
    });
    req.on("error", () => resolveBody(null));
  });
}

function clampInt(
  value: string | null,
  fallback: number,
  min: number,
  max: number,
): number {
  const n = value ? Number(value) : NaN;
  if (!Number.isFinite(n)) return fallback;
  return Math.min(max, Math.max(min, Math.floor(n)));
}
