/**
 * `control service` — boot persistence for the Mission Control plane via a
 * per-user systemd user unit (proposal 006, council loop #32).
 *
 * The in-process `--watchdog` restarts a stuck plane, but a machine reboot
 * kills both plane and watchdog; the unit starts `control serve` again at
 * login with the exact argv recorded in control.json. Linux-only for now:
 * other platforms get a clear unsupported error (launchd/Windows follow-up).
 *
 * No secrets ever enter the unit: the serve child reads the 0600 credential
 * file itself at boot, so ExecStart carries only paths and flags. systemctl is
 * always invoked with fixed argv (no shell).
 */

import { spawnSync } from 'node:child_process';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

export const SERVICE_UNIT_NAME = 'folderforge-control.service';

/**
 * One supervised-unit family (the control plane, a supervised MCP origin, …).
 * Generalized in proposal 009; the plane's spec (PLANE_UNIT) renders and
 * messages byte-identically to the original control-only implementation.
 */
export interface UnitSpec {
  /** systemd unit file name. */
  unitName: string;
  /** systemd Description= line. */
  description: string;
  /** CLI command shown in the unit header comment and failure hints. */
  generatedBy: string;
  /** Capitalized noun for messages ("Boot service", "Origin service"). */
  noun: string;
  /** Follow-up verification hint printed after enable. */
  verifyHint: string;
  /** Short CLI name for the unsupported-platform message. */
  cliName: string;
}

export const PLANE_UNIT: UnitSpec = {
  unitName: SERVICE_UNIT_NAME,
  description: 'FolderForge Mission Control plane',
  generatedBy: 'folderforge control service install',
  noun: 'Boot service',
  verifyHint: 'folderforge control service status',
  cliName: 'control service',
};

export interface SystemctlResult {
  exitCode: number;
  stdout: string;
  stderr: string;
}

export interface ServiceDeps {
  /** Absolute path of the node binary used in ExecStart. */
  execPath: string;
  /** User home directory (parent of the XDG fallback). */
  homeDir: string;
  /** Existence check — injected so tests can simulate a moved runtime. */
  fileExists: (path: string) => boolean;
  /** Run systemctl with fixed argv (no shell). */
  execSystemctl: (args: string[]) => SystemctlResult;
  /** Read an environment variable (XDG_CONFIG_HOME). */
  getEnv: (name: string) => string | undefined;
  platform: NodeJS.Platform;
  version: string;
}

export interface ServiceResult {
  output: string;
  exitCode: number;
}

/** State subset the unit is rendered from (mirrors the watchdog's serve argv). */
export interface ServiceStateLike {
  projectRoot: string;
  port: number;
  allow?: string[];
}

export function defaultSystemctl(args: string[]): SystemctlResult {
  const res = spawnSync('systemctl', args, { encoding: 'utf8' });
  return {
    exitCode: res.status ?? 1,
    stdout: res.stdout ?? '',
    stderr: res.stderr ?? (res.error ? String(res.error) : ''),
  };
}

export function unitFilePathFor(
  deps: Pick<ServiceDeps, 'getEnv' | 'homeDir'>,
  unitName: string,
): string {
  const xdg = deps.getEnv('XDG_CONFIG_HOME');
  const configHome =
    xdg !== undefined && xdg.trim().length > 0 ? xdg : join(deps.homeDir, '.config');
  return join(configHome, 'systemd', 'user', unitName);
}

export function unitFilePath(
  deps: Pick<ServiceDeps, 'getEnv' | 'homeDir'>,
): string {
  return unitFilePathFor(deps, SERVICE_UNIT_NAME);
}

/** systemd ExecStart quoting: bare when safe, else double-quoted (no shell). */
function quoteArg(arg: string): string {
  return /^[A-Za-z0-9_/=.,:@%+-]+$/.test(arg)
    ? arg
    : `"${arg.replace(/(["\\$`])/g, '\\$1')}"`;
}

export function renderUnit(
  serveArgs: string[],
  version: string,
  spec: UnitSpec = PLANE_UNIT,
  environmentFile?: string,
  environment?: Record<string, string>,
  oomScoreAdjust?: number,
  optionalEnvironmentFile?: string,
): string {
  if (
    oomScoreAdjust !== undefined &&
    (!Number.isInteger(oomScoreAdjust) || oomScoreAdjust < -1000 || oomScoreAdjust > 1000)
  ) {
    throw new Error(
      `Invalid oomScoreAdjust: ${String(oomScoreAdjust)} (expected an integer in -1000..1000).`,
    );
  }
  return [
    `# Generated by \`${spec.generatedBy}\` — edit via the CLI, not by hand.`,
    '[Unit]',
    `Description=${spec.description}`,
    'After=default.target',
    // StartLimit* live in [Unit]: older systemd ignores them in [Service].
    'StartLimitIntervalSec=60',
    'StartLimitBurst=5',
    '',
    '[Service]',
    `ExecStart=${serveArgs.map(quoteArg).join(' ')}`,
    // Optional environment mirroring (e.g. the origin's operator PATH):
    // Environment= lines precede EnvironmentFile= so the secrets file wins
    // any accidental key overlap.
    ...(environment !== undefined
      ? Object.entries(environment).map(([key, value]) =>
          // quoteArg covers only the KEY=VALUE assignment — the directive
          // name itself must stay bare for systemd to recognize it.
          `Environment=${quoteArg(`${key}=${value}`)}`,
        )
      : []),
    // Required (no `-` prefix): a missing secrets file must fail loudly.
    ...(environmentFile !== undefined ? [`EnvironmentFile=${quoteArg(environmentFile)}`] : []),
    // Optional (dash prefix): a missing operator env file never blocks boot.
    ...(optionalEnvironmentFile !== undefined
      ? [`EnvironmentFile=-${quoteArg(optionalEnvironmentFile)}`]
      : []),
    // Optional OOM protection for connection-critical units (e.g. -500).
    ...(oomScoreAdjust !== undefined ? [`OOMScoreAdjust=${oomScoreAdjust}`] : []),
    'Restart=on-failure',
    'RestartSec=5',
    '',
    '[Install]',
    'WantedBy=default.target',
    `# folderforge-version=${version}`,
    '',
  ].join('\n');
}

/** Extract the --project value from a rendered unit (overwrite guard + status). */
export function readUnitProject(unitText: string): string | undefined {
  const line = unitText.split('\n').find((l) => l.startsWith('ExecStart='));
  if (line === undefined) return undefined;
  const idx = line.indexOf('--project');
  if (idx === -1) return undefined;
  const rest = line.slice(idx + '--project'.length).trimStart();
  const m = /^"([^"]*)"|^(\S+)/.exec(rest);
  if (!m) return undefined;
  return m[1] ?? m[2];
}

function unsupportedPlatform(deps: ServiceDeps, spec: UnitSpec): ServiceResult {
  return {
    output:
      `${spec.cliName} is only supported on Linux (systemd user units); detected platform: ${deps.platform}. ` +
      'launchd/Windows support is a follow-up.\n',
    exitCode: 1,
  };
}

export interface InstallUnitOptions {
  /** Which unit family (name, description, wording) to render/install. */
  spec: UnitSpec;
  /** Full ExecStart argv (node binary + entry point + flags). */
  serveArgs: string[];
  /** Entry point validated before writing; omittable when runtimeFiles is set. */
  mainJs?: string;
  /** Run systemctl enable --now after writing the unit. */
  enable: boolean;
  /** Overwrite a unit owned by another project. */
  replace: boolean;
  /** Second success line (e.g. "Plane at login: project …, port …"). */
  detailLine: string;
  /** Optional 0600 secrets file wired in as a REQUIRED EnvironmentFile=. */
  environmentFile?: string;
  /** Optional Environment=KEY=VALUE lines (e.g. the origin mirrors PATH). */
  environment?: Record<string, string>;
  /** Replace the execPath/mainJs existence check entirely (e.g. tunnel units). */
  runtimeFiles?: string[];
  /** Optional OOMScoreAdjust= value (kernel range -1000..1000). */
  oomScoreAdjust?: number;
  /** Optional operator env file wired in as an OPTIONAL (dash-prefixed) EnvironmentFile=. */
  optionalEnvironmentFile?: string;
}

export function installUnit(
  options: InstallUnitOptions,
  deps: ServiceDeps,
): ServiceResult {
  const { spec } = options;
  if (deps.platform !== 'linux') return unsupportedPlatform(deps, spec);
  const runtimeFiles =
    options.runtimeFiles ??
    [deps.execPath, ...(options.mainJs !== undefined ? [options.mainJs] : [])];
  const missing = runtimeFiles.filter((file) => !deps.fileExists(file));
  if (missing.length > 0) {
    return {
      output:
        options.runtimeFiles === undefined
          ? `Runtime files are missing (node: ${deps.execPath}; app: ${options.mainJs}). ` +
            `Repair or upgrade the installation, then re-run \`${spec.generatedBy}\`.\n`
          : `Runtime files are missing (${missing.join(', ')}). ` +
            `Repair or upgrade the installation, then re-run \`${spec.generatedBy}\`.\n`,
      exitCode: 1,
    };
  }
  const unitPath = unitFilePathFor(deps, spec.unitName);
  const unit = renderUnit(
    options.serveArgs,
    deps.version,
    spec,
    options.environmentFile,
    options.environment,
    options.oomScoreAdjust,
    options.optionalEnvironmentFile,
  );
  const newProject = readUnitProject(unit);
  if (deps.fileExists(unitPath)) {
    const existingProject = readUnitProject(readFileSync(unitPath, 'utf8'));
    if (
      existingProject !== undefined &&
      newProject !== undefined &&
      existingProject !== newProject &&
      !options.replace
    ) {
      const noun = spec.noun.toLowerCase();
      return {
        output:
          `A ${noun} already exists for project ${existingProject}. ` +
          `Re-run with --replace to overwrite it (one ${noun} per user).\n`,
        exitCode: 1,
      };
    }
  }
  mkdirSync(dirname(unitPath), { recursive: true });
  writeFileSync(unitPath, unit, { mode: 0o600 });
  const lines = [
    `${spec.noun} installed: ${unitPath} (mode 0600, no secrets).`,
    options.detailLine,
  ];
  if (options.enable) {
    const steps = [
      ['--user', 'daemon-reload'],
      ['--user', 'enable', '--now', spec.unitName],
    ];
    for (const step of steps) {
      const res = deps.execSystemctl(step);
      if (res.exitCode !== 0) {
        lines.push(
          `systemctl ${step.join(' ')} failed (exit ${res.exitCode}): ${
            res.stderr.trim() || res.stdout.trim() || 'systemctl unavailable'
          }`,
        );
        return { output: lines.join('\n') + '\n', exitCode: 1 };
      }
    }
    lines.push(
      `Enabled and started via \`systemctl --user\`. Verify: ${spec.verifyHint}`,
    );
  } else {
    lines.push(
      `To enable: systemctl --user daemon-reload && systemctl --user enable --now ${spec.unitName}`,
    );
  }
  return { output: lines.join('\n') + '\n', exitCode: 0 };
}

export function installService(
  options: InstallOptions,
  deps: ServiceDeps,
): ServiceResult {
  if (deps.platform !== 'linux') return unsupportedPlatform(deps, PLANE_UNIT);
  const { state } = options;
  if (!state) {
    return {
      output:
        'No control plane state found. Run `folderforge control start` once first, ' +
        'so the boot service mirrors a known-good configuration.\n',
      exitCode: 1,
    };
  }
  const serveArgs = [
    deps.execPath,
    options.mainJs,
    'control',
    'serve',
    '--project',
    state.projectRoot,
    '--port',
    String(state.port),
    ...(state.allow ?? []).flatMap((dir) => ['--allow', dir]),
  ];
  return installUnit(
    {
      spec: PLANE_UNIT,
      serveArgs,
      mainJs: options.mainJs,
      enable: options.enable,
      replace: options.replace,
      detailLine: `Plane at login: project ${state.projectRoot}, port ${state.port} (loopback only).`,
      // Operator-managed env (e.g. CONTROL_PLANE_API_KEY for the ChatGPT
      // tunnel) may live in an optional 0600 file; a missing file never
      // blocks boot (dash-prefixed EnvironmentFile).
      optionalEnvironmentFile: join(state.projectRoot, '.folderforge', 'control.env'),
    },
    deps,
  );
}

export interface InstallOptions {
  /** control.json contents; null when the plane was never started. */
  state: ServiceStateLike | null;
  /** Run systemctl enable --now after writing the unit. */
  enable: boolean;
  /** Overwrite a unit owned by another project. */
  replace: boolean;
  mainJs: string;
}

export function uninstallUnit(deps: ServiceDeps, spec: UnitSpec): ServiceResult {
  if (deps.platform !== 'linux') return unsupportedPlatform(deps, spec);
  const unitPath = unitFilePathFor(deps, spec.unitName);
  if (!deps.fileExists(unitPath)) {
    return { output: `${spec.noun} is not installed; nothing to do.\n`, exitCode: 0 };
  }
  const notes: string[] = [];
  const disable = deps.execSystemctl(['--user', 'disable', '--now', spec.unitName]);
  if (disable.exitCode !== 0) {
    notes.push(
      `systemctl disable reported exit ${disable.exitCode}; removing the unit file anyway.`,
    );
  }
  rmSync(unitPath, { force: true });
  const reload = deps.execSystemctl(['--user', 'daemon-reload']);
  if (reload.exitCode !== 0) {
    notes.push('systemctl daemon-reload failed; run it manually if systemd is present.');
  }
  return {
    output: [`${spec.noun} uninstalled: ${unitPath}.`, ...notes].join('\n') + '\n',
    exitCode: 0,
  };
}

export function uninstallService(deps: ServiceDeps): ServiceResult {
  return uninstallUnit(deps, PLANE_UNIT);
}

export interface ServiceStatusInfo {
  installed: boolean;
  unitPath: string;
  projectRoot?: string;
  port?: number;
  enabled?: string;
  active?: string;
}

export function serviceStatusInfoFor(deps: ServiceDeps, unitName: string): ServiceStatusInfo {
  const unitPath = unitFilePathFor(deps, unitName);
  const info: ServiceStatusInfo = { installed: deps.fileExists(unitPath), unitPath };
  if (!info.installed) return info;
  const text = readFileSync(unitPath, 'utf8');
  const project = readUnitProject(text);
  if (project !== undefined) info.projectRoot = project;
  const portMatch = /--port\s+"?(\d+)"?/.exec(text);
  if (portMatch && portMatch[1] !== undefined) info.port = Number(portMatch[1]);
  const enabled = deps.execSystemctl(['--user', 'is-enabled', unitName]);
  info.enabled =
    enabled.exitCode === 0 ? enabled.stdout.trim() || 'enabled' : 'unknown';
  const active = deps.execSystemctl(['--user', 'is-active', unitName]);
  info.active = active.exitCode === 0 ? active.stdout.trim() || 'active' : 'unknown';
  return info;
}

export function serviceStatusInfo(deps: ServiceDeps): ServiceStatusInfo {
  return serviceStatusInfoFor(deps, SERVICE_UNIT_NAME);
}

export function serviceStatus(deps: ServiceDeps): ServiceResult {
  if (deps.platform !== 'linux') return unsupportedPlatform(deps, PLANE_UNIT);
  const info = serviceStatusInfo(deps);
  if (!info.installed) {
    return {
      output:
        `Boot service is not installed (${info.unitPath}).\n` +
        'Install: folderforge control service install\n',
      exitCode: 0,
    };
  }
  return {
    output:
      `Boot service installed: ${info.unitPath}\n` +
      `Target: project ${info.projectRoot ?? 'unknown'}, port ${info.port ?? 'unknown'}\n` +
      `systemd: enabled=${info.enabled ?? 'unknown'} active=${info.active ?? 'unknown'}\n`,
    exitCode: 0,
  };
}

/** One-line summary for `control status` (read-only; never fails the parent). */
export function serviceStatusLabel(deps: ServiceDeps): string {
  if (deps.platform !== 'linux') return 'n/a (linux only)';
  try {
    const info = serviceStatusInfo(deps);
    if (!info.installed) return 'not installed';
    return info.enabled ?? 'installed';
  } catch {
    return 'unknown';
  }
}
