import { detectProject, detectCommands, type ProjectInfo } from './project-detector.js';
import { MemoryStore } from './memory-store.js';

const TEMPLATE = (info: ProjectInfo, cmds: ReturnType<typeof detectCommands>) => {
  const overview = `# Project Overview: ${info.name}

- Root: ${info.projectRoot}
- Languages: ${info.languageHints.join(', ') || 'unknown'}
- Package managers: ${info.packageManagers.join(', ') || 'unknown'}
- Git: ${info.git ? 'yes' : 'no'}

_This file was generated by FolderForge onboarding. Edit freely._
`;

  const commands = `# Commands

- Package manager: ${cmds.packageManager ?? 'unknown'}
- Test framework: ${cmds.testFramework ?? 'unknown'}

| Task | Command |
| --- | --- |
${Object.entries(cmds.scripts)
  .map(([k, v]) => `| ${k} | \`${v}\` |`)
  .join('\n') || '| (none detected) | |'}
`;

  const conventions = `# Coding Conventions

- Detected languages: ${info.languageHints.join(', ') || 'unknown'}
- Add team conventions here (formatting, imports, naming, error handling).
`;

  const testing = `# Testing Strategy

- Framework: ${cmds.testFramework ?? 'unknown'}
- Run with: \`${cmds.scripts.test ?? 'TBD'}\`
- Describe coverage expectations and CI here.
`;

  return { overview, commands, conventions, testing };
};

export interface OnboardResult {
  project: ProjectInfo;
  commands: ReturnType<typeof detectCommands>;
  writtenMemories: string[];
}

export function onboardProject(root: string, memory: MemoryStore): OnboardResult {
  const project = detectProject(root);
  const commands = detectCommands(root);
  const t = TEMPLATE(project, commands);

  const existing = new Set(memory.list());
  const generated: Array<[string, string]> = [
    ['project_overview.md', t.overview],
    ['commands.md', t.commands],
    ['coding_conventions.md', t.conventions],
    ['testing_strategy.md', t.testing],
  ];
  const written: string[] = [];
  for (const [name, content] of generated) {
    if (!existing.has(name)) written.push(memory.write(name, content));
  }

  return { project, commands, writtenMemories: written };
}
