/**
 * Per-folder MCP fleet provisioner (ADR-0012, Phase 1).
 *
 * Manages a bounded fleet of FolderForge MCP instances, one per project folder.
 * Instances are spawned through the existing ProcessManager (injected here), so
 * Mission Control process containment and write-freeze keep working unchanged.
 *
 * Secret discipline: bearer tokens are returned exactly once at creation or
 * rotation. The fleet state file stores only SHA-256 token hashes; the raw
 * token lives solely in the per-instance config file (mode 0600), and both the
 * state file and the config directory are covered by DEFAULT_DENIED_GLOBS so
 * native agent file tools cannot read them.
 */

import { createHash, randomBytes, randomUUID } from 'node:crypto';
import {
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { basename, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export type FleetInstanceState = 'stopped' | 'starting' | 'running' | 'stopping' | 'failed';

export interface FleetInstance {
  id: string;
  name: string;
  projectPath: string;
  port: number;
  toolsPreset: string;
  policyMode: string;
  /** SHA-256 of the instance bearer token. The raw token is never persisted. */
  tokenSha256: string;
  /** Restart automatically after an unexpected exit (rate-limited). */
  autoRestart?: boolean;
  state: FleetInstanceState;
  sessionId?: string;
  pid?: number;
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  lastError?: string;
}

export interface FleetSpawnResult {
  sessionId: string;
  pid: number | undefined;
}

export type FleetSpawner = (command: string, cwd: string) => FleetSpawnResult;
export type FleetSessionStopper = (sessionId: string) => unknown;
export type FleetLogReader = (sessionId: string) => string;
/** Probe an instance endpoint; resolves true when it answers and enforces auth. */
export type FleetHealthProbe = (port: number) => Promise<boolean>;
/** Check whether a pid refers to a live process. */
export type FleetPidAlive = (pid: number) => boolean;
/** Subscribe to a managed session's exit; returns an unsubscribe function. */
export type FleetExitSubscribe = (sessionId: string, listener: () => void) => () => void;

export interface FleetHealth {
  id: string;
  state: FleetInstanceState;
  pidAlive: boolean;
  endpointOk: boolean;
  healthy: boolean;
}

export interface FleetManagerOptions {
  spawn?: FleetSpawner;
  stopSession?: FleetSessionStopper;
  readSession?: FleetLogReader;
  probe?: FleetHealthProbe;
  isAlive?: FleetPidAlive;
  onExit?: FleetExitSubscribe;
  /** Entrypoint of the built runtime; defaults to <dist>/main.js. */
  mainJs?: string;
  /** Hard cap on provisioned instances (operator-controlled, not agent-set). */
  maxFleet?: number;
  portRange?: { start: number; end: number };
  /** Minimum delay between automatic restarts of the same instance. */
  autoRestartCooldownMs?: number;
  now?: () => number;
}

export const FLEET_TOOLS_PRESETS = ['vibe', 'vibe-lite', 'readonly', 'full', 'godot'] as const;
export const FLEET_POLICY_MODES = ['readonly', 'safe', 'dev', 'danger'] as const;

const DEFAULT_MAX_FLEET = 8;
const DEFAULT_PORT_START = 7410;
const DEFAULT_PORT_END = 7499;

interface PersistedFleetState {
  schemaVersion: 1;
  instances: FleetInstance[];
}

function sha256(value: string): string {
  return createHash('sha256').update(value).digest('hex');
}

/** JSON.stringify output is a valid YAML double-quoted scalar. */
function yamlString(value: string): string {
  return JSON.stringify(value);
}

function instanceConfigYaml(record: FleetInstance, token: string): string {
  return [
    '# Generated by the FolderForge fleet provisioner. Contains a bearer token.',
    '# Mode 0600; the path matches DEFAULT_DENIED_GLOBS so agent file tools cannot read it.',
    'server:',
    `  name: ${yamlString(`folderforge-fleet-${record.id}`)}`,
    '  transport: http',
    '  http:',
    '    host: "127.0.0.1"',
    `    port: ${record.port}`,
    `    token: ${yamlString(token)}`,
    '    requireAuth: true',
    '  dashboard:',
    '    enabled: false',
    'workspace:',
    `  defaultProject: ${yamlString(record.projectPath)}`,
    '  allowedDirectories:',
    `    - ${yamlString(record.projectPath)}`,
    'policy:',
    `  defaultMode: ${yamlString(record.policyMode)}`,
    '',
  ].join('\n');
}

/** Default endpoint probe: the instance is up when /mcp answers and enforces auth. */
async function defaultEndpointProbe(port: number): Promise<boolean> {
  try {
    const response = await fetch(`http://127.0.0.1:${port}/mcp`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        accept: 'application/json, text/event-stream',
      },
      body: JSON.stringify({ jsonrpc: '2.0', id: 0, method: 'initialize', params: {} }),
      signal: AbortSignal.timeout(3000),
    });
    return response.status === 200 || response.status === 401;
  } catch {
    return false;
  }
}

/** Default liveness check for a spawned pid. */
function defaultPidAlive(pid: number): boolean {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

export class FleetManager {
  private readonly statePath: string;
  private readonly fleetDir: string;
  private readonly mainJs: string;
  private readonly maxFleet: number;
  private readonly portStart: number;
  private readonly portEnd: number;
  private readonly spawnFn: FleetSpawner | undefined;
  private readonly stopFn: FleetSessionStopper | undefined;
  private readonly readFn: FleetLogReader | undefined;
  private readonly probeFn: FleetHealthProbe;
  private readonly isAliveFn: FleetPidAlive;
  private readonly onExitFn: FleetExitSubscribe | undefined;
  private readonly autoRestartCooldownMs: number;
  private readonly lastAutoRestart = new Map<string, number>();
  private readonly now: () => number;
  private instances: FleetInstance[] = [];

  constructor(projectRoot: string, options: FleetManagerOptions = {}) {
    const stateDir = resolve(projectRoot, '.folderforge');
    this.statePath = resolve(stateDir, 'fleet.json');
    this.fleetDir = resolve(stateDir, 'fleet');
    this.mainJs =
      options.mainJs ?? resolve(dirname(fileURLToPath(import.meta.url)), '..', 'main.js');
    this.maxFleet = options.maxFleet ?? DEFAULT_MAX_FLEET;
    this.portStart = options.portRange?.start ?? DEFAULT_PORT_START;
    this.portEnd = options.portRange?.end ?? DEFAULT_PORT_END;
    this.spawnFn = options.spawn;
    this.stopFn = options.stopSession;
    this.readFn = options.readSession;
    this.probeFn = options.probe ?? defaultEndpointProbe;
    this.isAliveFn = options.isAlive ?? defaultPidAlive;
    this.onExitFn = options.onExit;
    this.autoRestartCooldownMs = options.autoRestartCooldownMs ?? 60_000;
    this.now = options.now ?? (() => Date.now());
    this.load();
  }

  list(): FleetInstance[] {
    return this.instances.map((instance) => ({ ...instance }));
  }

  get(id: string): FleetInstance {
    return { ...this.mutable(id) };
  }

  create(input: {
    projectPath: string;
    name?: string;
    port?: number;
    toolsPreset?: string;
    policyMode?: string;
    actor?: string;
  }): { instance: FleetInstance; token: string } {
    const projectPath = resolve(input.projectPath);
    if (!existsSync(projectPath) || !statSync(projectPath).isDirectory()) {
      throw new Error(`Not a project folder: ${projectPath}`);
    }
    if (this.instances.some((instance) => instance.projectPath === projectPath)) {
      throw new Error(`Folder already provisioned: ${projectPath}`);
    }
    if (this.instances.length >= this.maxFleet) {
      throw new Error(`Fleet cap reached (${this.maxFleet} instances). Destroy one first.`);
    }
    const port = input.port ?? this.allocatePort();
    this.assertPort(port);
    const toolsPreset = input.toolsPreset ?? 'vibe';
    if (!(FLEET_TOOLS_PRESETS as readonly string[]).includes(toolsPreset)) {
      throw new Error(`Unknown tools preset: ${toolsPreset} (allowed: ${FLEET_TOOLS_PRESETS.join(', ')})`);
    }
    const policyMode = input.policyMode ?? 'dev';
    if (!(FLEET_POLICY_MODES as readonly string[]).includes(policyMode)) {
      throw new Error(`Unknown policy mode: ${policyMode} (allowed: ${FLEET_POLICY_MODES.join(', ')})`);
    }

    const id = `flt_${randomUUID().slice(0, 8)}`;
    const token = randomBytes(32).toString('base64url');
    const timestamp = new Date(this.now()).toISOString();
    const instance: FleetInstance = {
      id,
      name: input.name?.trim() || basename(projectPath),
      projectPath,
      port,
      toolsPreset,
      policyMode,
      tokenSha256: sha256(token),
      state: 'stopped',
      createdAt: timestamp,
      createdBy: input.actor?.trim() || 'unknown',
      updatedAt: timestamp,
    };

    mkdirSync(this.fleetDir, { recursive: true });
    writeFileSync(this.configPathFor(id), instanceConfigYaml(instance, token), { mode: 0o600 });
    this.instances.push(instance);
    this.persist();
    return { instance: { ...instance }, token };
  }

  start(id: string): FleetInstance {
    const record = this.mutable(id);
    if (record.state === 'running' || record.state === 'starting') {
      throw new Error(`Instance ${id} is already ${record.state}.`);
    }
    if (!this.spawnFn) {
      throw new Error('No process spawner is wired; fleet start is unavailable.');
    }
    if (!existsSync(this.mainJs)) {
      throw new Error('FolderForge runtime entrypoint not found; run `npm run build` first.');
    }
    record.state = 'starting';
    delete record.lastError;
    this.persist();
    try {
      const session = this.spawnFn(this.startCommand(record), record.projectPath);
      record.state = 'running';
      record.sessionId = session.sessionId;
      if (session.pid !== undefined) record.pid = session.pid;
      if (this.onExitFn) {
        this.onExitFn(session.sessionId, () => this.handleExit(id, session.sessionId));
      }
    } catch (error) {
      record.state = 'failed';
      record.lastError = error instanceof Error ? error.message : String(error);
      this.persist();
      throw error;
    }
    this.touch(record);
    this.persist();
    return { ...record };
  }

  stop(id: string): FleetInstance {
    const record = this.mutable(id);
    if (record.state === 'stopped') return { ...record };
    if (record.sessionId && this.stopFn) {
      record.state = 'stopping';
      try {
        this.stopFn(record.sessionId);
      } catch {
        // The session may already be gone; the record still converges to stopped.
      }
    }
    record.state = 'stopped';
    delete record.sessionId;
    delete record.pid;
    this.touch(record);
    this.persist();
    return { ...record };
  }

  rotateToken(id: string): { instance: FleetInstance; token: string; restartRequired: boolean } {
    const record = this.mutable(id);
    const token = randomBytes(32).toString('base64url');
    record.tokenSha256 = sha256(token);
    writeFileSync(this.configPathFor(id), instanceConfigYaml(record, token), { mode: 0o600 });
    this.touch(record);
    this.persist();
    return {
      instance: { ...record },
      token,
      restartRequired: record.state === 'running' || record.state === 'starting',
    };
  }

  destroy(id: string): { destroyed: string } {
    const record = this.mutable(id);
    if (record.state !== 'stopped' && record.state !== 'failed') {
      throw new Error(`Stop instance ${id} before destroying it (state: ${record.state}).`);
    }
    const configPath = this.configPathFor(id);
    if (existsSync(configPath)) unlinkSync(configPath);
    this.instances = this.instances.filter((instance) => instance.id !== id);
    this.persist();
    return { destroyed: id };
  }

  logs(id: string): string {
    const record = this.mutable(id);
    if (!record.sessionId || !this.readFn) return '';
    return this.readFn(record.sessionId);
  }

  /** Probe one instance: policy state, pid liveness, and HTTP auth enforcement. */
  async health(id: string): Promise<FleetHealth> {
    const record = this.mutable(id);
    const pidAlive = record.pid !== undefined ? this.isAliveFn(record.pid) : false;
    const endpointOk = record.state === 'running' ? await this.probeFn(record.port) : false;
    return {
      id: record.id,
      state: record.state,
      pidAlive,
      endpointOk,
      healthy: record.state === 'running' && pidAlive && endpointOk,
    };
  }

  /** Restart an instance: graceful stop followed by start. */
  restart(id: string): FleetInstance {
    this.stop(id);
    return this.start(id);
  }

  /** Enable or disable automatic restart after an unexpected exit. */
  setAutoRestart(id: string, enabled: boolean): FleetInstance {
    const record = this.mutable(id);
    record.autoRestart = enabled;
    this.touch(record);
    this.persist();
    return { ...record };
  }

  /**
   * Handle an unexpected process exit. Deliberate stops pass through
   * `stopping`/`stopped` first, so a `running` state here means a crash.
   * Auto-restart is rate-limited per instance to avoid restart loops.
   */
  private handleExit(id: string, sessionId: string): void {
    const record = this.instances.find((instance) => instance.id === id);
    if (!record || record.sessionId !== sessionId) return; // stale session
    if (record.state !== 'running') return; // deliberate stop
    record.state = 'failed';
    record.lastError = 'Process exited unexpectedly.';
    delete record.sessionId;
    delete record.pid;
    this.touch(record);
    this.persist();
    if (!record.autoRestart) return;
    const last = this.lastAutoRestart.get(id) ?? 0;
    if (this.now() - last < this.autoRestartCooldownMs) return;
    this.lastAutoRestart.set(id, this.now());
    try {
      this.start(id);
    } catch {
      // The record stays failed; start() already captured the reason in lastError.
    }
  }

  private mutable(id: string): FleetInstance {
    const record = this.instances.find((instance) => instance.id === id);
    if (!record) throw new Error(`Unknown fleet instance: ${id}`);
    return record;
  }

  private allocatePort(): number {
    const used = new Set(this.instances.map((instance) => instance.port));
    for (let port = this.portStart; port <= this.portEnd; port += 1) {
      if (!used.has(port)) return port;
    }
    throw new Error(`No free fleet port in range ${this.portStart}-${this.portEnd}.`);
  }

  private assertPort(port: number): void {
    if (!Number.isInteger(port) || port < 1024 || port > 65535) {
      throw new Error(`Invalid port: ${port} (expected an integer in 1024-65535).`);
    }
    if (this.instances.some((instance) => instance.port === port)) {
      throw new Error(`Port ${port} is already assigned to another fleet instance.`);
    }
  }

  private startCommand(record: FleetInstance): string {
    return [
      JSON.stringify(process.execPath),
      JSON.stringify(this.mainJs),
      '--project',
      JSON.stringify(record.projectPath),
      '--config',
      JSON.stringify(this.configPathFor(record.id)),
      '--no-dashboard',
      '--policy',
      record.policyMode,
      '--tools-preset',
      record.toolsPreset,
    ].join(' ');
  }

  private configPathFor(id: string): string {
    return resolve(this.fleetDir, `${id}.yaml`);
  }

  private touch(record: FleetInstance): void {
    record.updatedAt = new Date(this.now()).toISOString();
  }

  private load(): void {
    if (!existsSync(this.statePath)) return;
    const parsed = JSON.parse(readFileSync(this.statePath, 'utf8')) as PersistedFleetState;
    if (parsed.schemaVersion !== 1 || !Array.isArray(parsed.instances)) {
      throw new Error(`Unsupported fleet state schema in ${this.statePath}.`);
    }
    this.instances = parsed.instances;
  }

  private persist(): void {
    mkdirSync(dirname(this.statePath), { recursive: true });
    const tmp = `${this.statePath}.${randomUUID().slice(0, 8)}.tmp`;
    const state: PersistedFleetState = { schemaVersion: 1, instances: this.instances };
    writeFileSync(tmp, JSON.stringify(state, null, 2), { mode: 0o600 });
    renameSync(tmp, this.statePath);
  }
}
